### ISSUE TITLE
Watchman is running at a lower than normal priority.

### ISSUE THREAD

**Issue by YajanaRao** [facebook/watchman#1015]
I am getting this error on `react-native start`.

I have tried  `watchman --no-spawn --no-local shutdown-server`. Did not help.

The version is `2220410.024423.0`

Watchman is running at a lower than normal priority. Since that results in poor performance that is otherwise very difficult to trace, diagnose and debug, Watchman is refusing to start.
Fatal error detected at:
(error retrieving stack trace

![image](https://user-images.githubusercontent.com/38914337/163419356-5f107bfc-5022-444a-bf85-fde812cb058f.png)

**Comment by edavetisyan** [comment]
same issue

**Comment by MichaelCuevas** [comment]
The code that's preventing watchman from running is here: https://github.com/facebook/watchman/blob/main/watchman/main.cpp#L93-L98

You can tweak the `min_acceptable_nice_value` in your `/etc/watchman.json`

You could also try starting react-native with a higher nice value :)

**Comment by xxxserxxx** [comment]
Thanks; I just delete the entire check.

**Comment by MusfiqDehan** [comment]
Nothing is working for me. Even I didn't find any `etc/watchman.json` file. 
So I have to remove the full `watchman` package. I am using linux, the command I use to remove `watchman` is:
``` 
sudo apt remove watchman
```
After that I run the below command to update the repositories:

```
sudo apt update && sudo apt autoremove && sudo apt autoclean
```
Now everything is working perfectly. My app is running.

_**Note:** I know this is not an ideal solution. If anyone find any better solution, please comment in this issue so that everyone can be benefited._

**Comment by IncrediblePony** [comment]
If you end up in a situation like me, where I don't have watchman installed through apt, but in a yarn package, the following may help:

- If you have just updated a lot of packages on your system (i.e. `sudo apt update && sudo apt upgrade` or `flatpak update`) try rebooting you system.
- Remove and reinstall your android emulator through AVD. I have no idea why, but this have also helped me out a few times.
