### ISSUE TITLE
Build fails on Ubuntu 22.04

### ISSUE THREAD

**Issue by floratmin** [facebook/watchman#1047]
I tried to build watchman but the build fails with:

```
[53/213] Building Rust executable 'watchmanctl'...
FAILED: watchman/cli/CMakeFiles/watchmanctl.cargo watchman/cli/debug/watchmanctl watchman/cli/release/watchmanctl 
cd /home/florian/Downloads/watchman/watchman/cli && /tmp/fbcode_builder_getdeps-ZhomeZflorianZDownloadsZwatchmanZbuildZfbcode_builder/installed/cmake-qU6QoPESYZej5AcCTHDEVvZkEMvpc5Lijp-LQSq8PeE/bin/cmake -E remove -f /home/florian/Downloads/watchman/watchman/cli/Cargo.lock && /tmp/fbcode_builder_getdeps-ZhomeZflorianZDownloadsZwatchmanZbuildZfbcode_builder/installed/cmake-qU6QoPESYZej5AcCTHDEVvZkEMvpc5Lijp-LQSq8PeE/bin/cmake -E env CARGO_TARGET_DIR=/tmp/fbcode_builder_getdeps-ZhomeZflorianZDownloadsZwatchmanZbuildZfbcode_builder/build/watchman/watchman/cli cargo build --release -p watchmanctl
No such file or directory
[67/213] Building CXX object CMakeFiles/pendingcollection.t.dir/watchman/test/PendingCollectionTest.cpp.o
ninja: build stopped: subcommand failed.
Command '['/tmp/fbcode_builder_getdeps-ZhomeZflorianZDownloadsZwatchmanZbuildZfbcode_builder/installed/cmake-qU6QoPESYZej5AcCTHDEVvZkEMvpc5Lijp-LQSq8PeE/bin/cmake', '--build', '/tmp/fbcode_builder_getdeps-ZhomeZflorianZDownloadsZwatchmanZbuildZfbcode_builder/build/watchman', '--target', 'install', '--config', 'Release', '-j', '16']' returned non-zero exit status 1.
!! Failed

```

**Comment by micaelgomes** [comment]
I had same issue, so I purged watchman installed from the source and get package from apt, using: `sudo apt -y install watchman
`

**Comment by stewartmatheson** [comment]
I'm having the same issue running ubuntu on WSL. I'm running the `autogen.sh` script.

**Comment by jeffryang24** [comment]
Maybe you can try manually installing the missing `libcrypto.so.1.1` lib from `libssl1.1` package before running watchman cli. See https://github.com/facebook/watchman/issues/1019#issuecomment-1263343842. Hopefully, it solves your problem too :bow:

**Comment by chadaustin** [comment]
We now automatically generate Ubuntu 22.04 debs. You can download and install them with the new installation instructions at https://facebook.github.io/watchman/docs/install.html

I recommend against the Ubuntu-provided package, because it's missing security fixes.

I think the _specific_ build error you're seeing is that `cargo` is not installed so the Rust components fail to build. If you install Rustup via `https://rustup.rs/` it should work.

I'll close this for now, and add a better error message if `cargo` is not available.

**Comment by jose8a** [comment]
There are zero Ubuntu 22 debs at the latest release link. I've been trying to install from source and keep running into errors. I will probably just use the Ubuntu-provided ones since I'm left without any other current choices. If the debs are now elsewhere than in the release link that is provided, then please advise. Thanks!

**Comment by iamvladshevchuk** [comment]
I'm also running into issues while trying to install it on Ubuntu 24.04. I'm installing it via `./autogen.sh`. I ran `./install-system-packages.sh` before the command.

```
[62/217] Building CXX object CMakeFiles/eden_config_thrift.dir/eden/fs/config/gen-cpp2/eden_config_types.cpp.o
ninja: build stopped: subcommand failed.
Command '['/usr/bin/cmake', '--build', '/tmp/fbcode_builder_getdeps-ZhomeZai40ZDownloadsZwatchman-2024.12.09.00ZbuildZfbcode_builder-root/build/watchman', '--target', 'install', '--config', 'RelWithDebInfo', '-j', '12']' returned non-zero exit status 1.
!! Failed
```

Documentation states:

> From the [latest release](https://github.com/facebook/watchman/releases/latest), download the .deb corresponding to your Ubuntu version

But [latest release (v2024.12.09.00)](https://github.com/facebook/watchman/releases/tag/v2024.12.09.00) doesn't have .deb file.

Do you have any advice for me? What should I do to install watchman?
