### ISSUE TITLE
Linux PopOS! 22.04 [Ubuntu based] - Rust and Cargo dependency

### ISSUE THREAD

**Issue by gsdiniz** [facebook/watchman#1061]
I am trying to build watchman using autogen.sh file in PopOS! 22.04.

But the process always fails in the build of watchman and watchmanctl because Cargo is not installed.

After I installed them using this => https://rustup.rs/
the build of watchman finally worked.

This dependency in not listed or informed in any docs.

**Comment by chadaustin** [comment]
Ah, good point. I just reproduced this experience and it's pretty confusing indeed. Ninja fails with an error and it's hard to tell exactly why.

I'll change the CMake build to fail early if `cargo` cannot be found.

In terms of documentation - is there a particular place you wish this had been written down?

**Comment by gsdiniz** [comment]
In the Building from Source section or be installed automatic by install-system-packages.sh file.

``
set -x
python3 "$(dirname "$0")/build/fbcode_builder/getdeps.py" install-system-deps --recursive watchman
``

**Comment by chadaustin** [comment]
OK, I'll update the installation page to mention that too. We probably don't want to automatically install cargo, since there isn't one obvious installation source. Some people prefer it from the OS package manager, and some from https://rustup.rs

Thanks! This should close automatically when the fix lands.
