### ISSUE TITLE
Request: allow for fine-grained matching against the filesystem events in expressions

### ISSUE THREAD

**Issue by yassinelabidi** [facebook/watchman#125]
It would be nice to have the ability to either query or trigger commands, based a specific fs event: create, delete, close, move, etc. If I am not mistaken, from the standpoint of watchman, all of these are abstracted as a 'change' event.

**Comment by wez** [comment]
We deliberately chose not to try to expose events at that level of granularity.  Unlike other watchers, watchman's primary purpose is to build a map of the current state of the filesystem and remember when each file was last changed.  This allows accelerating a common question asked by various tools.

To be able to provide consistent and conservative results in the face of either restarts or kernel notification queue overflows (where we have to re-crawl a directory) and because filesystem operations are fraught with TOCTOU race conditions, we track only that a file was changed (or possibly changed) and not the nature of the change itself.

In addition, different operating systems provide different levels of support for these various events that make it more complex to correct model and verify behavior.

It would be difficult to add support for this.  I'm not saying "no", but am questioning whether it is worth the time to do so.

What is your use case for wanting this additional level of granularity?

**Comment by yassinelabidi** [comment]
Thank you for the feedback. My use case for the time being is watching for newly created log files and triggering processing commands on them (tailing and piping to a consumption pipeline). And it might involve watching for other types of events in the near future like closing or removing a file.

**Comment by wez** [comment]
Watchman can tell you enough about all of these things that you can build that today, except for when a file is closed.  It's also worth noting that file close notifications are not portable across operating systems.

**Comment by yassinelabidi** [comment]
Agreed. But in that case, is there a way for instance, to trigger a command only when a file is created, and not on subsequent modifications? As far as I can tell, the current set of expression terms is not likely to express that in straightforward way.

**Comment by wez** [comment]
There are a couple of ways to determine which files were recently created.

If you are issuing a query directly you can issue a `since` generator based query and inspect the `new` field in the results:

```js
["query", "/some/path", {
    "since": "n:lastcheck",
    "expression": ["true"],
}]
```

You'll get results like:

```js
{
    "clock": "c:80616:59",
    "is_fresh_instance": false,
    "files": [
        {
            "exists": true,
            "mode": 33188,
            "new": false,
            "name": "argv.c",
            "size": 1340,
        }
    ]
}
```

(the same results apply to the file list generated by triggers too -- see more below)

The `new` field will be true if watchman considers the file to have been created more recently than the logical point in time specified by the `since` parameter; read more about [clockspecs](http://facebook.github.io/watchman/docs/clockspec.html).

Note that watchman will also consider a file as being new when it first observes the file existing; this will happen when the watch is initiated and also if it needs to [recrawl](http://facebook.github.io/watchman/docs/troubleshooting.html#recrawl).  In these cases the result set is considered to be a *fresh instance* result set and you can express to watchman how you wish to be notified about it; there's a section on that that isn't easily linked to in the [since generator docs](http://facebook.github.io/watchman/docs/file-query.html#since-generator)

The other way to find newly created files is to use the [since expression term](http://facebook.github.io/watchman/docs/expr/since.html) and specify that you're interested in changes to either the `ctime` or `cclock` (created clock) information that watchman maintains.  This is a bit more clunky than just using the since generator instead.

We should add an expression term that selects only `new` nodes.

For now, your triggered command will need to inspect the `new` field in the returned files and react accordingly; use the [extended syntax](http://facebook.github.io/watchman/docs/cmd/trigger.html#extended-syntax) and request a json input stream:

```
["trigger", "/some/path", {
   "name": "mytriggername",
   "expression": ["true"],
   "command": ["my_command"],
   "append_files": false,
   "stdin": ["name", "new"]
}]
```

Then in your implementation of `my_command`, decode stdin as JSON and parse out the information about the files.

**Comment by yassinelabidi** [comment]
Thanks a lot! That gives me good starting points to evaluate it.
