### ISSUE TITLE
License of HTML docs

### ISSUE THREAD

**Issue by nodakai** [facebook/watchman#144]
Is it correct to understand that all the HTML files in the `gh-pages` branch are released under Apache2, too?  If so, is it possible to add a small note explicitly stating so under the name of Facebook, Inc. perhaps to the end of index.html?

I'm packaging watchman for Debian.

**Comment by wez** [comment]
Everything in this github repo, on every branch in the repo, falls under the same license unless individual files state otherwise (there are a couple that have a slightly different license to accommodate being used with Mercurial).  If it will make things simpler, we'll be happy to accept a PR that adds a `<meta>` tag to the `website/_includes/head.html` template that points to our `LICENSE` file.

**Comment by wez** [comment]
Closing due to lack of feedback.  Please re-open when you're ready to revisit this.
