### ISSUE TITLE
watcher library

### ISSUE THREAD

**Issue by lpgauth** [facebook/watchman#147]
Hi,
I'm interested in the watcher library part of the project, not the watchman service. Would splitting it up (watcher vs watchman) in two project something you guys would consider?

Thanks,
LP

**Comment by sid0** [comment]
Do you mean the pywatchman/node-watchman libraries? They're available on npm/pypi. To make changes you can clone the repo -- it's not that bug.

**Comment by lpgauth** [comment]
No, I mean the watchman system layer that wraps inotify, kqueue, fsevents, etc.

https://github.com/facebook/watchman/tree/master/watcher

**Comment by sid0** [comment]
I'm going to let @wez make the decision here, but I personally don't think we want to sign up for any API stability guarantees.

**Comment by sid0** [comment]
(You are, of course, free to copy/paste the code into your project as long as you respect the license terms.)

**Comment by wez** [comment]
I think the bigger question is, what are you planning on using it for?  And by that I mean, is there a use case that watchman could do a better job at meeting?

Our watcher internals are pretty specific to our internal architecture, and that architecture doesn't really lend itself to being embedded.  This is by design; one of the major benefits of using Watchman is that we can consolidate the watches into one portable service and avoid exhausting the overall number of system watch resources.

As @sid0 mentioned, we're not super thrilled to commit to API stability for something that we consider to be an internal implementation detail.

I have been thinking about adding a C/C++ client library for watchman to make it easier to consume.  Is that more along the lines of your use case?  Could you share more about what you had in mind?

**Comment by wez** [comment]
I'm going to close this out for now; if you want to continue a dialogue, please re-open it :)
