### ISSUE TITLE
watch-project freedom

### ISSUE THREAD

**Issue by mattdipasquale** [facebook/watchman#154]
Sometimes, I enjoy the freedom of coding without version control.

It's like walking naked in a desert... very relaxing.

I'm using `watch-project` (to watch and compile JavaScript files) on a subproject (`Web`) inside a project that *is* under version control.

The directory structure looks like this:

```
|__MyApp
|____.git
|____Clients
|______Android
|______iOS
|______Web
|____Servers
|______Chat
|______Database
|______REST
```

Am I right that, for what I'm doing, `Web` should be considered the project root and not `MyApp`?

`Web` doesn't need a `.watchmanconfig`, so I'd rather not have to create a blank one.

I realize I could make each of the six subprojects (Clients: Android, iOS, Web; Servers: Chat, Database, REST) its own git repository, but right now, I'm changing lots of files in different subprojects and committing once is faster than committing six times. Every commit adds up.

Right now, the source code exists only on my laptop. I mostly work alone, or when I do work with others, we pair on my laptop. Sure, if things develop enough down the line, then six separate repos may make sense.

I'd use `watch`, but saw that it's deprecated.

So, what am I to do?

What if there were an environment variable or option I could use to explicitly set the root directory? That way, inside `Web`, I could run a command like:

    WATCHMAN_ROOT=. watchman watch-project .

or

    watchman watch-project --root=. .

respectively.

Or, what about adding other files to the default `root_files`, such as: `README*`, `Project.json`, `Brewfile`, `Gemfile`, `Makefile`, `Rakefile`, etc.?

**Comment by wez** [comment]
Should `Web` be the root?  The answer to that is that it depends on how self-contained you consider the `Web` dir to be.  If you have build/tooling dependencies that rely on things under `MyApp` that are outside of `Web`, then I'd suggest just taking `MyApp` as the root.

Otherwise: If you want the `Web` dir to be seen as the root for a project not managed in source control, you'll need to provide a hint to watchman.  The `.watchmanconfig` file is the (literally) definitive way to identify a project root; it takes precedence over any of the files that you might choose to list in the `root_files` configuration.  You can, of course, choose to populate your `root_files` configuration on your system to list out the files that you consider to be indicative of a project root.

We're rather selective about what goes in the default `root_files`, because making it match too many things is more limiting than making it match fewer.  It would break several projects at FB if we adopted the list that you suggest above.

Regarding setting things by environment, or otherwise making it a parameter at watch time that is out of band of statically located information from the configuration files; that results in non-deterministic behavior for starting a watch and that is something that we want to avoid in tools.

It sounds like the two least intrusive options for you are:

1. Create a file containing `{}` in `/path/to/MyApp/Clients/Web/.watchmanconfig`, and run `watchman watch-project /path/to/MyApp/Clients/Web`.  This will generate a watch on that dir directly (although if any of the parent dirs are already being watched it will then return that dir and the offset to your web dir) and will work with other tools that use `watch-project` to consolidate watches (those tools include things like Buck, Nuclide, React-Native, ember-cli).
2. You can just do `watchman watch /path/to/MyApp/Clients/Web`.  If you don't need to work with any of the tools I mentioned above, and you don't employ the `root_restrict_files` configuration locally or in any of the places that your `Web` project will be worked on, then you can happily continue to use `watch` in this way.   We consider it deprecated in favor of `watch-project`, but per https://facebook.github.io/watchman/docs/compatibility.html, it is going to be available and work the same way forever.

I'd encourage you to go with option 1 if you're likely to share that project, but otherwise, go wild and enjoy your freedom to use option 2 :-)

**Comment by mattdipasquale** [comment]
Thank you @wez for the thorough reply. I got option 2 working for now and will switch to option 1 if need be. :-)

**Comment by wez** [comment]
Enjoy!
