### ISSUE TITLE
failed to create /var/run/watchman/cstrahan-state: No such file or directory

### ISSUE THREAD

**Issue by cstrahan** [facebook/watchman#178]
I'm trying to update our `watchman` package in [NixOS](https://github.com/NixOS/nixpkgs), but `watchman` wants to create `$prefix/var/lib/watchman` at install time. Nix (and other "pure" package managers like [Guix](http://www.gnu.org/software/guix/) don't allow for packages to touch directories like `/var/run` (packages are built within a `chroot` and only have access to their own `$prefix`). I've tried changing the state directory to something like `/tmp/watchman`, but `watchman` fails with:

    2015-10-23T13:47:11,933: [1275692800] failed to create /tmp/watchman/cstrahan-state: No such file or directory

Something must have changed since version 3.0, because this isn't a problem with that version. Actually, from just glancing at `watchman get-sockname` on 3.0, it looks like the state dir is essentially `/tmp/.watchman.$USER`, which watchman happily creates.

Should I patch our sources to revert to the old behavior, or would you consider adapting the state dir handling to support packaging with Nix/Guix/etc?

**Comment by cstrahan** [comment]
Ah, never mind - I realize now that I can use `--disable-statedir` and `watchman` will create `/tmp/$USER-state`. Not sure why the naming scheme was changed, but I suppose this will do.

Thanks!

**Comment by wez** [comment]
We changed the state dir to harden against a possible symlink attack (the state file, socket and log file could be redirected to some other location via a symlink to trick watchman into writing some place else).

It is important to have the sticky bit set on the statedir to help protect against this, which is why we didn't keep things in `/tmp`.  You can change the statedir by doing `--enable-statedir=myprefix/foo` but you do need to keep in mind that there is a maximum practical length of approx 100 characters for unix domain socket names, so you don't want the path to be too deep.

**Comment by cstrahan** [comment]
> We changed the state dir to harden against a possible symlink attack (the state file, socket and log file could be redirected to some other location via a symlink to trick watchman into writing some place else).

Interesting - thanks for the explanation. IIUC, you're saying that, in the case where you're running `watchman` as a daemon, an attacker could set up a symlink in order to cause the daemon to clobber important files.

I suppose that's only relevant if you're using `watchman` as a daemon; what exactly is the rationale for doing so? Having a smaller footprint by having one process, rather than a process per user with possibly overlapping watches/indexes/etc (along with the requisite kernel resources)?

On NixOS, while packages are required to be immutable, *services* may have state. Thus, in NixOS, I think we could provide a binary that uses `/tmp` by default, but the service would use the `--sockname`/`--logfile`/`--statefile` flags to effectively make the "statedir" be `/var/lib/watchman`, with the sticky bit set. Enabled services can also add to the system's shell profile, so it would be trivial for us to set up a `watchman` alias that passes the right flags.

Ultimately, I don't want us to have to choose between a binary that doesn't work without the service running, or a binary that works without but is susceptible to attack when run as `root`.

**Comment by wez** [comment]
Watchman is a per-user service.  The CLI spawns a server if there isn't one running for the current user.

We have this per-user (rather than a global root-owned process for the whole system) because it makes it much simpler to implement a service that has access to your files without having to deal with funky stuff like root_squash on NFS, or making rock solid authentication, or dealing with the fsuid on linux.

We run as a daemon rather than as an in-process library for two reasons:

1. The daemon can be persistent and understand changes that happen outside the lifetime of tools, such as mercurial, that are not running persistently.  This can help accelerate them.
2. The daemon can consolidate watches for your user across multiple tool invocations.  For example, mercurial and Buck can share those watch resources and reduce the amount of kernel memory required to manage large directory trees

This model is similar in some ways to tmux or screen which have long running per-user processes that can be addressed via a socket in a well known path.

**Comment by cstrahan** [comment]
@wez Thanks for the explanation. I probably should have worded my questions as "I suppose that's only relevant if you're using watchman as ***a root-owned*** daemon". I want to make sure that our package isn't insecure, but I wasn't exactly sure what threat was being mitigated with the changes since `3.0.0`.

And thanks again for writing/maintaining `watchman` :).
