### ISSUE TITLE
How to restart script every time script is changed using Watchman?

### ISSUE THREAD

**Issue by SuperManEver** [facebook/watchman#185]
I using watchman while working on the web project using sinatra framework. I start app using 'ruby app.ru' command from command line. Is it possible to make watchman to watch for files in the current folder and below in the tree and restart 'ruby app.rb' every time any files is changed?

**Comment by wez** [comment]
Yep, there are two ways to launch a script when something changes:

The first is using [triggers](https://facebook.github.io/watchman/docs/cmd/trigger.html).  These are most appropriate if you don't care about seeing the output from the script.  It's a bit awkward to use triggers in an ad-hoc manner so...

The second is using the new [watchman-make](https://facebook.github.io/watchman/docs/watchman-make.html) tool, which runs in the foreground and lets you see the output.  `watchman-make` hasn't made it into `homebrew` yet (https://github.com/Homebrew/homebrew/pull/45548 is the PR for that), so if you want to try it immediately, you may need to do a bit of poking around:

```
brew install --HEAD watchman
```

and then see this comment: https://github.com/facebook/watchman/issues/184#issuecomment-152599517

Now, since you want to restart an existing program, you'll want to write a little script that does something like:

```bash
#!/bin/bash

# kill off old version, avoid killing random ruby processes
pkill -f 'ruby app.rb'
# run it again but don't wait for it to finish
ruby app.rb &
disown
```

This feels a bit kludgey; there's a chance that you'll kill something else that is running `ruby app.rb` (seems likely if that is the pattern for kicking off ruby apps), so you may want to build something a bit more robust; the usual way to do that is to have your app save its process id into a file and then have the restart script kill the pid from that file.  I'll leave that as an exercise for you ;-)

Stringing things together; using triggers:

```bash
cd /path/to/app
watchman watch $PWD
watchman trigger -j <<EOT
["trigger", "$PWD", {
   "name": "restart-app",
   "command": "restart.sh"
}]
EOT
```

Any changed file will then cause `restart.sh` to be run and the output will land in the watchman log file.
To turn it off you'll need to run `watchman trigger-del restart-app`.

Using watchman-make:

You'll need to dance around the fact that this is geared more towards running a tool like `make`.  We'll set `--make` to `restart.sh` so that it runs that instead of make.  The `-t` option specifies the target name; it doesn't matter for this use case, so we're using `ignored`.  To trigger on every file we use the `-p '**/*'` option to match any file at any depth in the tree.

So this:

```bash
watchman-make --make './restart.sh' -p '**/*' -t ignored
```

will cause `./restart.sh ignored` to be run whenever any file is changed in the current dir.

**Comment by wez** [comment]
watchman 4.1.0 is now available in homebrew, so this simplifies things, I'll edit my comment above

**Comment by SuperManEver** [comment]
Thank you, that's exactly what I needed.
