### ISSUE TITLE
'warning' is not defined in watchman-make

### ISSUE THREAD

**Issue by alfa07** [facebook/watchman#207]
```
❯ watchman-make --settle 1.0 --make 'hstags.sh' --pattern '**/*.hs' --target tags
# Relative to /Users/maxim/Dev/ComputationGeometry/LineSegmentIntersection
Traceback (most recent call last):
  File "/usr/local/Cellar/watchman/4.1.0/libexec/bin/watchman-make", line 175, in <module>
    t.start(client, root)
  File "/usr/local/Cellar/watchman/4.1.0/libexec/bin/watchman-make", line 48, in start
    warning(watch['warning'])
NameError: global name 'warning' is not defined
```

**Comment by wez** [comment]
Going out in version 4.4

**Comment by victoriastuart** [comment]
FYI, I encountered this error today (I am a new "watchman-make" user) -- installed on Arch Linux via AUR/pacaur: "watchman"; "python2-pywatchman" (latter provides watchman-make: https://aur.archlinux.org/packages/python2-pywatchman/).  I was getting this error,

```
Traceback (most recent call last):
  File "/usr/bin/watchman-make", line 175, in <module>
    t.start(client, root)
  File "/usr/bin/watchman-make", line 48, in start
    warning(watch['warning'])
NameError: global name 'warning' is not defined

```
Soluion: pacaur installs watchman, watchman-make as sudo; therefore, you need to run watchman-make as sudo (i.e.: sudo watchman-make).

Added, in case it helps others.

**Comment by wez** [comment]
@victoriastuart you should almost never run watchman with sudo.  The security model is designed so that each user has their own watchman server process that only allows connections from that user.   I'd recommend that you run:

```
sudo watchman shutdown-server
```

to stop the root owned instance.  Then you will need to remove the root-owned files from the state dir (https://facebook.github.io/watchman/docs/troubleshooting.html#where-are-the-logs has information on how to locate this).

```
sudo rm -rf STATEDIR
```

With that done, you should then be able to use watchman and watchman-make as yourself.

Note that the error message from this issue was fixed several releases ago; I'd also recommend that you run the most recently released version, because the `warning` that is it trying to print will have some context about what is really not working for your installation.

**Comment by victoriastuart** [comment]
Hi; thanks for your reply; appreciated.

```
$ sudo watchman shutdown-server
{
    "version": "4.7.0",
    "shutdown-server": true
}
```
That's the current version, no?  :-/

Anyway, I ran both those commands (above) and now I'm right back to this error (running as regular user):

```
[victoria@victoria javascript]$ wmj
  [watchman-make (javascript)]
# Relative to /home/victoria/projects/javascript
Traceback (most recent call last):
  File "/usr/bin/watchman-make", line 175, in <module>
    t.start(client, root)
  File "/usr/bin/watchman-make", line 48, in start
    warning(watch['warning'])
NameError: global name 'warning' is not defined
[victoria@victoria javascript]$
```
FYR, "wmj" is my .bashrc alias to

```
watchman-make -p '*.js' --make 'node js_sp.js' -t ''
```
