### ISSUE TITLE
Watchman freezes OS temporarily after running it

### ISSUE THREAD

**Issue by HenryVonfire** [facebook/watchman#217]
Every time I run `watchman 4.1` in `Opensuse 13.2` it freezes the OS for about 5 minutes or more to the point that I can only move the mouse. It also happens when I shut it down and start it again. I installed it from the sources, what could be the reason of this freezing?

**Comment by wez** [comment]
Can you clarify what you mean by SO?

Please run through the troubleshooting information here:
https://facebook.github.io/watchman/docs/troubleshooting.html

It will be useful to understand more about the environment in which you're running; how large is the tree, are you using a spinning disk, how many CPUs do you have, do you have a large number of files that you don't want to watch and may want to ignore, does anything interesting show up in the logs and so on.  How are you using watchman?  Are you using hgwatchman or some or other tool, or using it directly?

It may also be the case that using the latest version of watchman has much better results; I'd recommend using the current master branch so that you pick up an important linux specific change that was pushed in the past day or so.

**Comment by HenryVonfire** [comment]
Sorry, I meant OS (Operating System). `Opensuse 13.2` gets completely frozen except for the mouse.  It's a laptop with 4 CPU's and a spinning disk. I'm using watchman with `ember-cli`, no special configurations, just the default installation. `ember-cli` uses it automatically and the only thing I've done is to increase the size of  the `max_user_watches` to `131072` because of a `inotify` warning I got in the beginning while using it.

The tree can be pretty huge since I have some ember projects with their own `node_modules` folders filled (which tend to be a lot of files and folders). The strange thing is that it happens only on the first run. After that I can keep working with it without problems but if I reboot or shutdown `watchman` and launch it again, it frozen the OS again.

**Comment by wez** [comment]
There's a couple of things I'd like you to do:

1.  Upgrade to watchman 4.5  (you'll need to build from source per https://facebook.github.io/watchman/docs/install.html#installing-from-source)
2.  Install Google Perf Tools (I believe the package is named google-perftools on Opensuse)
3.  Run: `watchman watch-del-all` and wait for your system to settle (this clears out all watches so that we can have a baseline)
4.  In a window of its own, run `perf record g -p $(pgrep watchman)`.  This will sample the watchman process behavior; it will keep running until you interrupt it.  Leave it running across the next step.
5. Start your ember build process
6. Once the ember build is done, switch back to the window where you're running `perf` and hit CTRL-C
7. Collect the output from `perf report -g -G --stdio` into a gist and share it with me.  That will show me where it is spending its time.

That will help us figure out the next steps

**Comment by HenryVonfire** [comment]
Some of your steps must have resolved the problem because this time it didn't freeze the OS. In any case, here's the `perf report`: https://gist.github.com/HenryVonfire/f816a168de2c4b79aba8

**Comment by wez** [comment]
Ah, the debug symbols aren't present there.

If you have performance problems that are traced back to watchman in the future, there's one additional step; enable debugging symbols.  You can do this by changing your configure invocation to something like:

```
CFLAGS="-g -O2" LDFLAGS="-g" ./configure <arguments here>
```

However, since it sounded like upgrading resolved your issue, let's close this out.

**Comment by HenryVonfire** [comment]
Thank you very much for your help :)
