### ISSUE TITLE
watchman-make: add --run option as alternative to --make

### ISSUE THREAD

**Issue by sebm** [facebook/watchman#232]
I use watchman-make to automatically trigger a script on filesystem changes, which I've accomplished in a fairly hacky way:

> `watchman-make -p '**/*.js' '**/*.css' --make my_script.sh -t ''`

The `-t ''` is necessary because otherwise I get the error

> # No targets were specified, nothing to do.

Would you consider allowing an empty target or at least a `--no-target` flag for this kind of use case? I could even write it myself, I just want to make sure it conforms to your design standards.

**Comment by wez** [comment]
It works this way because it is intended to be used primarily with a build tool that you can instruct to make (potentially) multiple different targets.

I'm amenable to making a simpler UI for non-make use cases, how about something like:

```
watchman-make -p '**/*.js' '**/*.css' --run my_script.sh
```

that will just run `my_script.sh` when any of the matching patterns change.

Does that sound good to you?  If so, would you like to submit a pull request to implement that?

**Comment by sebm** [comment]
Hey @wez, that would work for me. I'm amenable to making a pull request when I get a chance…watch this space.

**Comment by wez** [comment]
Looking forward to it, thanks!

**Comment by joseluisq** [comment]
@wez `--run` option is a great idea.
But, Is there any alternative way to do this with the current release?
Thanks.

**Comment by wez** [comment]
@joseluisq the original post shows exactly how to do this today

**Comment by joseluisq** [comment]
> @joseluisq the original post shows exactly how to do this today

Yeah works thanks!

**Comment by TDAbboud** [comment]
I got around to implementing this feature and submitted a PR. I would appreciate any feedback.

**Comment by joseluisq** [comment]
@TDAbboud awesome!

**Comment by wez** [comment]
This will be included in the 4.8 release which should happen in the next week or so

**Comment by sebm** [comment]
Thank you @TDAbboud !
