### ISSUE TITLE
Is it possible store watchman-make flags in config?

### ISSUE THREAD

**Issue by a93ushakov** [facebook/watchman#245]
?

**Comment by wez** [comment]
We don't really want to make it stateful.  I'm assuming you want to avoid remembering the flags, so here are some options:

- If you already have a Makefile, just add a `watch` rule.  We do this in watchman itself: https://github.com/facebook/watchman/blob/master/Makefile.am#L215
- You can write a little shell script that just runs watchman-make with the right flags for your project.  You could call it `watch.sh` and commit it into your repo alongside the rest of your code in that project
- You can use the alias feature of your shell to make a shortcut so that you don't need to think or type so hard next time around

**Comment by a93ushakov** [comment]
Thank you for great reply.
