### ISSUE TITLE
How to automatically kill previous build execution if new file change detected ?

### ISSUE THREAD

**Issue by a93ushakov** [facebook/watchman#246]
I use `watchman` for auto-rebuilding `latex` document on new changes, but if `latex` returns error - `watchman doesn't` restart building.

Can someone help to fix it?

P.S. It's possible to write `bash` script that use `inotify-wait` and `bash` job system for killing old build.
How to get such result with `watchman`?

**Comment by wez** [comment]
Can you provide more details about what isn't working?
What version of watchman do you have? Run `watchman version` and share the output.
How are you running `watchman-make`?
What is the error, and are you changing any files after the error?
Can you give an example of a file change that isn't triggering your build?

Note that we also have https://facebook.github.io/watchman/docs/watchman-wait.html which is similar to `inotify-wait`.  You can use it if you prefer.

**Comment by a93ushakov** [comment]
```make
document.pdf: document.tex bibliography.bib
  pdflatex -shell-escape document.tex
  bibtex document
  pdflatex -shell-escape document.tex
  pdflatex -shell-escape document.tex
```

```sh
watchman-make -p document.tex -t document.pdf
```

If `latex` abort building due error - it show in interactive mode error message and offer, for example, enter some data for problem fixing. 
In this case `watchman` after new file change don't kill stopped due error building.

For job handling `bash jobs` can be used (in env var pid can be stored and used for killing stopped building and restarting).

**Comment by wez** [comment]
Just to make sure I understand, are you asking for a new feature like this?

* Add a command line flag called something like `--respawn-on-file-changes` that will cause `watchman-make` to kill the spawned child process and restart it if changes are detected while waiting for the build to finish

I'm a little confused by your comments about interactive behavior; could you clarify what happens there?  When an error happens, is latex prompting you to manually resolve it?  If so, are you actually resolving it interactively, or terminating it?  Do you expect `watchman-make` to trigger the rebuild based on the build failure or based on files changing as part of your interactive resolution?

Is the problem the interactivity in latex?  If so, can you disable that through a command line flag?

**Comment by a93ushakov** [comment]
https://asciinema.org/a/6gbp63fahi5van0gqwv9apb4z

Adding `-interaction=nonstopmode` flag solves the problem, but, as I understand, `watchman` after change detecting creates new subshell - and `watchman` should kill this subshell - and it does not matter interactive it or no.

There is also another solution - use `docker` containers for job starting and killing - but it's overhead, as I think.

So, `--respawn-on-file-changes` is a great idea.

> Do you expect watchman-make to trigger the rebuild based on the build failure or based on files changing as part of your interactive resolution?
Sounds interesting. How trigger can detects failed build? By return code?

**Comment by wez** [comment]
Thanks for sharing that screen capture! I understand what's happening now.

The way that `watchman-make` works is quite simple: it waits for a triggering condition (the files that match the patterns you requested) and then it executes your command using the python `subprocess.call` function.  That function blocks until your command completes.

There isn't anything for watchman to kill in the current mode of operation; once the command has finished, it has been waited on and there are no outstanding resources to collect or kill.

The `-interaction=nonstopmode` flag is what it sounds like you needed to make things work well here; if/when that process fails it causes the `make` process to fail and then `subprocess.call` returns in the `watchman-make` process, allowing it to wait for the next file triggering event.

`--respawn-on-file-changes` is something I'd really like to avoid; build steps often generate files that match your triggering pattern (consider a compiler generator running to update a `.c` file), and such a flag would likely cause the build to terminate at a non-deterministic point, and likely while useful work is in progress.

Restarting the build after a failure, based on the exit status of the build, is also something I'd like to avoid because it would likely just result in looping the build until you fixed a build problem, and you can make that happen just by running `make` in a `while` loop :-)

I asked about both of these to try to understand better what you were experiencing and what you were looking to change.

**Comment by a93ushakov** [comment]
But in some cases `--respawn-on-file-changes` can be useful. It's an option, by default it can be disabled.

So, let's assume that there isn't `-interaction=nonstopmode` flag in `pdflatex`, and build process takes several hours.

If I edit document, `watchman` detects it and invokes building.
I made another change - and I must wait when previous unnecessary build finished?

**Comment by a93ushakov** [comment]
P.S. current `watchman-make` syntax is not comfortable relatively `make` variables. 
This will not work:
```sh
watchman-make -p 'file0, file1, file2' -t build
```

Works if
```sh
watchman-make -p 'file0' 'file1' 'file2' -t build
```

Here  spaces in `make` var converted to commas, but it's impossible (I'am not sure) to insert quotes for `watchman-wait` work.
 
```make
  pdflatex -interaction=nonstopmode -shell-escape exam.tex

 comma:= ,
 empty:=
 space:= $(empty) $(empty)
 bar:= $(subst $(space),$(comma),$(DEPS))
.PHONY serve:
  watchman-make -p "$(bar)" -t exam.pdf
```

**Comment by wez** [comment]
re: really long builds: `watchman-make` is most useful when the builds are relatively short and you want to automatically run and see the results as you're hacking on something.  If the build takes a substantial amount of time, you probably do not want to have the build start automatically.   One of the challenges with adding a `--respawn-on-file-changes` option is that `watchman-make` then needs to be deal with threading to be able to manage the child process and deal with change notifications.  It's adds quite a lot of complexity and doesn't help with the most highly leveraged use case, which is to have your build + tests run quickly and automatically in another window as you work.

re: patterns question, I would phrase your invocation like this, assuming that `images` is a dir containing images:

```
.PHONY serve:
   watchman-make -p '*.tex' '*.bib' 'images/**' -t exam.pdf
```

this way you don't need to change the watchman invocation very often as you expand the scope of your document.
