### ISSUE TITLE
 ERROR: f2d_register_rpc() => (null) (-22)

### ISSUE THREAD

**Issue by caixindong** [facebook/watchman#339]

**Comment by wez** [comment]
There's not a lot of information in this issue.
Did you work through the troubleshooting for the similar error mentioned there?

https://facebook.github.io/watchman/docs/troubleshooting.html#fseventstreamstart-register_with_server-error-f2d_register_rpc-gt-null-21

**Comment by caixindong** [comment]
When I installed watchman,I got  a error:whether we are cross compiling... configure: error: in `/private/tmp/xz-20160819-5741-uh7tbt/xz-5.2.2':
configure: error: cannot run C compiled programs.
My system version is OS X 10.12 , watchman don't have a following version?

**Comment by wez** [comment]
There are no details in your report that I can use to help you, you need to provide a lot more information so that we can understand what you are doing and what the errors are.

Please start by running through the troubleshooting steps I linked to above and reporting what you've tried and what happened.

If that doesn't resolve your issue, we'll need to see your log files (information about those is also in the troubleshooting guide).

Regarding the compiler related error, that's not a watchman problem: that's something specific to your environment and we cannot provide support for getting a working compiler.

**Comment by wez** [comment]
Closing out for now; if/when you get around to providing the information requested above, please add it to this issue and re-open it.
