### ISSUE TITLE
autogen.sh not found?

### ISSUE THREAD

**Issue by rohmanhm** [facebook/watchman#364]
I using **Bash on Ubuntu on Windows** in Windows 10

When I run `./autogen.sh` then show this error

```cli
RohmanHM@MHR-PC:/mnt/d/Hybrid/watchman$ ./autogen.sh
./autogen.sh: 9: ./autogen.sh: aclocal: not found
./autogen.sh: 10: ./autogen.sh: autoheader: not found
./autogen.sh: 11: ./autogen.sh: automake: not found
./autogen.sh: 12: ./autogen.sh: autoconf: not found

**Comment by wez** [comment]
Please check the first paragraph of https://facebook.github.io/watchman/docs/install.html#installing-from-source
You need to install some development packages.

Since you are probably the first person to try this configuration, and because inotify running on windows is unproven, I'd recommend that you run `make integration` to run the integration tests to verify that inotify works.

Please let us know the outcome of this!

**Comment by rohmanhm** [comment]
Wow, I have installed Watchman on my Windows PC with **Bash on Ubuntu on Windows**

```cli
root@MHR-PC:/mnt/d/Hybrid/watchman# watchman --help
Usage: watchman [opts] command

 -h, --help                 Show this help

     --inetd                Spawning from an inetd style supervisor

 -v, --version              Show version number

 -U, --sockname=PATH        Specify alternate sockname

 -o, --logfile=PATH         Specify path to logfile

     --log-level            set the log level (0 = off, default is 1, verbose = 2)

     --pidfile=PATH         Specify path to pidfile

 -p, --persistent           Persist and wait for further responses

 -n, --no-save-state        Don't save state between invocations

     --statefile=PATH       Specify path to file to hold watch and trigger state

 -j, --json-command         Instead of parsing CLI arguments, take a single json object from stdin

     --output-encoding=ARG  CLI output encoding. json (default) or bser

     --server-encoding=ARG  CLI<->server encoding. bser (default) or json

 -f, --foreground           Run the service in the foreground

     --no-pretty            Don't pretty print JSON

     --no-spawn             Don't try to start the service if it is not available

     --no-local             When no-spawn is enabled, don't try to handle request in client mode if service is unavailable


Available commands:

      clock
      debug-ageout
      debug-drop-privs
      debug-poison
      debug-recrawl
      debug-show-cursors
      find
      get-config
      get-pid
      get-sockname
      list-capabilities
      log
      log-level
      query
      shutdown-server
      since
      state-enter
      state-leave
      subscribe
      trigger
      trigger-del
      trigger-list
      unsubscribe
      version
      watch
      watch-del
      watch-del-all
      watch-list
      watch-project

See https://github.com/facebook/watchman#watchman for more help

Watchman, by Wez Furlong.
Copyright 2012-2015 Facebook, Inc.

**Comment by sid0** [comment]
inotify doesn't currently work in that environment, so watchman isn't going to work either.

- Siddharth




On Sun, Sep 18, 2016 at 3:52 PM -0700, "Muhammad Habib Rohman" <notifications@github.com<mailto:notifications@github.com>> wrote:


Wow, I have installed Watchman on my Windows PC with Bash on Ubuntu on Windows

root@MHR-PC:/mnt/d/Hybrid/watchman# watchman --help
Usage: watchman [opts] command

 -h, --help                 Show this help

     --inetd                Spawning from an inetd style supervisor

 -v, --version              Show version number

 -U, --sockname=PATH        Specify alternate sockname

 -o, --logfile=PATH         Specify path to logfile

     --log-level            set the log level (0 = off, default is 1, verbose = 2)

     --pidfile=PATH         Specify path to pidfile

 -p, --persistent           Persist and wait for further responses

 -n, --no-save-state        Don't save state between invocations

     --statefile=PATH       Specify path to file to hold watch and trigger state

 -j, --json-command         Instead of parsing CLI arguments, take a single json object from stdin

     --output-encoding=ARG  CLI output encoding. json (default) or bser

     --server-encoding=ARG  CLI<->server encoding. bser (default) or json

 -f, --foreground           Run the service in the foreground

     --no-pretty            Don't pretty print JSON

     --no-spawn             Don't try to start the service if it is not available

     --no-local             When no-spawn is enabled, don't try to handle request in client mode if service is unavailable


Available commands:

      clock
      debug-ageout
      debug-drop-privs
      debug-poison
      debug-recrawl
      debug-show-cursors
      find
      get-config
      get-pid
      get-sockname
      list-capabilities
      log
      log-level
      query
      shutdown-server
      since
      state-enter
      state-leave
      subscribe
      trigger
      trigger-del
      trigger-list
      unsubscribe
      version
      watch
      watch-del
      watch-del-all
      watch-list
      watch-project

See https://github.com/facebook/watchman#watchman for more help

Watchman, by Wez Furlong.
Copyright 2012-2015 Facebook, Inc.


-

**Comment by wez** [comment]
I'm closing this out because it was a local environment issue.  Per @sid0's comment above, we don't expect watchman to function correctly in that environment, so you may want to switch to the real (alpha) watchman build for windows.  More details on that can be found in #19
