### ISSUE TITLE
Java library uses API from JDK 1.7

### ISSUE THREAD

**Issue by styurin** [facebook/watchman#414]
Java library claims to be compiled with [language level 1.6](https://github.com/facebook/watchman/blob/master/java/BUCK#L11-L12) but it uses classes from JDK 1.7 (`java.nio.file.Path`).

Need to decide which language level we want to support and fix this discrepancy.

**Comment by mkillianey** [comment]
The very first commit for this Java library was f3e69138fd7af21b77afc33eb44576c37e64fcc9 , and in that commit it already required Java 1.7.  Since it's never been open-sourced in a state that would be operational under 1.6 (and since 1.6 is already way past end of life), I cannot imagine who would be broken if we just fess up that the Java library has required 1.7 this whole time.

**Comment by wez** [comment]
I'm fine with raising the advertised req to 1.7+

**Comment by wez** [comment]
This got taken care of by https://github.com/facebook/watchman/commit/a76a0d4aa277123197774c112ad93a0edc2e6d25
