### ISSUE TITLE
High memory usage on OSX

### ISSUE THREAD

**Issue by jcollum** [facebook/watchman#415]
It's using more memory than Webstorm: 

![image](https://cloud.githubusercontent.com/assets/704514/21720321/3f73d264-d3d7-11e6-9016-8c6990d62608.png)

```
$ versions
npm 3.10.8
node v6.9.1
OS:
ProductName:	Mac OS X
ProductVersion:	10.11.6
BuildVersion:	15G31
```

I'm not even sure why watchman is running. Atom/Nuclide is closed and I don't have any React-Native stuff running at all; no packager, no simulator, no XCode, no Android Studio. 

I don't have any node processes running either, other than pm2. Which, I suppose, could be using watchman, but there is only one process running under pm2 and it doesn't have watching turned on.

**Comment by wez** [comment]
Watchman maintains the watches persistently.  Memory utilization correlates with the number of files and dirs that are being watched.  If you run `watchman watch-list` you'll see what it is watching.  You can run `watchman watch-del-all` to cancel them all, and `watchman shutdown-server` to stop watchman (until a tool next asks it to start up)

**Comment by jcollum** [comment]
I killed it this morning. It's back now and the usage is at 2.49GB. I looked into it and it's watching `~` -- no wonder it's usage is high. However, I have no idea how it got set to watch that folder. Is this triggered by Nuclide somehow? 

Ran `$ watchman watch-del ~` and the usage is down to 88MB.  I do want to know what's triggering it though. I have not run watchman from the command line, ever,  IIRC

**Comment by wez** [comment]
The default configuration for watchman is to have it try to aggregate watches at a git, mercurial or svn repo.  If you have a repo in your home directory (some folks do this to keep track of their dotfiles) then this may be what is happening.

If you don't want your home dir to be watched, then you have a couple of options.

1.  Place a `.watchmanconfig` file at the root of what you consider to be the project for your React Native or Nuclide usage.  This will short-circuit the walk that finds your home dir and stop at the dir that contains the `.watchmanconfig` file.  This should work fine provided that those tools are not explicitly trying to operate on your home dir.

2. Create a file named `/etc/watchman.json` with the contents:

```
{
   "root_files": [".watchmanconfig"],
   "enforce_root_files": true
}
```

This will only allow watching a directory that has a .watchmanconfig file in it or in its parents.  This is how we have watchman configured on Facebook systems and should work just fine with Nuclide and React Native.

You will need to run `watchman shutdown-server` each time you change `/etc/watchman.json` for the changes to take effect.

https://facebook.github.io/watchman/docs/config.html#root_files has the relevant documentation for this.

**Comment by jcollum** [comment]
> some folks do this to keep track of their dotfiles

ding ding ding

>/etc/watchman.json

So should that be ` ~/etc/watchman.json` or `~/work/project/etc/watchman.json`? Because I've done the latter along with .watchmanconfig and restarted watchman and it's still using >2GB.

This is just my opinion man but Watchman is being far too aggressive here. I should have to explicitly turn on this sort of behavior. I'm not even sure how watchman got started -- I assume it's part of Nuclide. 

Using 2.4GB of memory for behavior that **I didn't ask for** is too much. Do you get that? Do you see why a process that just showed up without me asking then using >2GB of memory is a bit obnoxious? 

So here's what I did: 

1. place .watchmanconfig in root folder
1. place `watchman.json` in `~/etc`
1. results: 
```
$ cat ~/.watchmanconfig 
{}
$ cat ~/etc/watchman.json 
{
   "root_files": [".watchmanconfig"],
   "enforce_root_files": true
}
```
1. do the two steps above for my project folder (react native project edited with Atom)
1. shutdown watchman: `watchman shutdown-server` in bash 
1. well that last step hung up so I just killed the process 
1. watch processes
1. watchman comes back 
1. watchman starts using up memory
1. watchman is at ~~1.36GB~~ 1.74GB and climbing as I write this

My project is not big enough to justify almost 2GB of memory for a file watcher. This is silly.

**Comment by sid0** [comment]
> So should that be ~/etc/watchman.json or ~/work/project/etc/watchman.json? Because I've done the latter along with .watchmanconfig and restarted watchman and it's still using >2GB.

Just `/etc/watchman.json`. As in, in a file called `watchman.json` in the `/etc` directory in the root of your system.

**Comment by sid0** [comment]
I'm sorry to hear that you're having trouble and understand your frustration, but making your entire home directory version controlled has never been a good idea. Only a it number of users do it, and it has always had the potential to break tools that assume you're in a source repository anywhere in your home directory.

What we recommend (in general, not just for watchman) is to move your dotfiles to a subdirectory of your home directory (say `~/dotfiles`), then set up symlinks (e.g. `~/.bashrc -> ~/dotfiles/.bashrc`). That works just as well to version your dotfiles while not having the chance to confuse any tools.

**Comment by sid0** [comment]
> I have to make a file in my etc folder to turn off your tool? That I never turned on to begin with? This is completely opposite of every other watch tool I've used in the node.js ecosystem.

That file in `/etc` is for configuration. `/etc` is a standard location for system-wide configuration of Unix tools.

It may make sense to also have per-user configuration, but that need hasn't arisen yet and you are the first one to ask for it.

> This is completely obnoxious. How do I uninstall this tool completely?

We're sorry to see you go. Please uninstall the tool using whatever means you installed it. (For example, if you installed it with homebrew, use that to uninstall it.) You will also have to stop using and uninstall any other tools that have a hard dependency on it, of course, like (I believe) Nuclide.

> I have no need of it and don't like it. I can't actually tell you what it's doing or why I would need it.

From our [documentation](http://facebook.github.io/watchman/):

> Watchman exists to watch files and record when they change. It can also trigger actions (such as rebuilding assets) when matching files change.

**Comment by jcollum** [comment]
> Watchman exists to watch files and record when they change

I have tools that do this (nodemon, gulp). They: 

1. don't require me to config via `/etc`; I'd expect that out of a database, not a dev support tool
1. don't eat up 2GB of memory
1. aren't aggressively watching git repos that I didn't tell them to watch
1. don't "just show up" and start making assumptions about what I want them to watch

I have to assume watchman came in via nuclide. 

I'm annoyed but I guess the path of least resistance is just to make that file in /etc/configuration. 

I recommend asking the user to do that as part of the install so they don't accidentally run into this ~~bug~~ unintended behavior.

**Comment by wez** [comment]
I'm sorry that you got frustrated with this.  I feel like you turned pretty hostile on us and we'd barely gotten started with helping you understand and resolve your issue.

If you do decide to keep watchman installed, and really don't like putting your configuration in `/etc`, I think we should look again at where you placed the `.watchmanconfig` file.  From one of your comments it sounded like you had placed that in your home dir.  That isn't what you want in this case because it is just confirming to watchman that the home dir should be a watch point, and we've established that you don't want to pay the cost of watching that.

For example, if you put your source code under `~/src` and are happy with Nuclide and watchman keeping track of everything under there, then I would recommend creating `~/src/.watchmanconfig` and removing the one you placed in `~/.watchmanconfig`, then running `watchman watch-del-all`.

Regarding the other filesystem watchers that you compared watchman against: watchman was designed to to be fast to query in very large filesystem trees.  Watchman intentionally uses RAM to ensure that the responses are fast and are not constrained by the lackluster performance of the VFS layer in macOS.  The persistent monitoring is an important component of this because it takes too long to rebuild that in-memory database of information from scratch with the size of directory tree that we work with.  The persistent model makes watchman extremely reliable when compared to in-process subscription based watchers that are common in the nodejs ecosystem.

It is understandable that these differences took you by surprise.

The default configuration in watchman has been "good enough" for the majority of our users so far.  We do recognize that it would be good to allow more control over this sort of thing, and have been tracking some brief thoughts on this in https://github.com/facebook/watchman/issues/202.  It just hasn't come up often up for us to raise the priority on this so far.

**Comment by rjain15** [comment]
thanks, I changed to the /etc/watchman.json and my memory usage dropped from 600 MB to 26 MB. I believe this should be a default option when you install watchman to create a /etc/watchman.json file and let users add directories/files to watch.
