### ISSUE TITLE
WatchMan script Does not work!

### ISSUE THREAD

**Issue by skaushikWebuy** [facebook/watchman#420]
```
================================= 
Getting Success on running in logs
==================================
watchman watch /home/sachin/works/test

watchman -j <<-EOT
["trigger", "/home/sachin/works/test", {
  "name": "ImageLookout",  
  "command": ["/home/sachin/works/run.sh"]
}]
EOT
========================
Contents of run.sh
=========================
php /home/sachin/works/dbinsert.php


This line for trigger too does not work

"expression": ["pcre", "^[.*](jpeg|jpg|png|gif)$"],
```

**Comment by sid0** [comment]
How did you build Watchman? The 'pcre' line will only work if you configured it with `--enable-pcre`.

**Comment by skaushikWebuy** [comment]
ok agreed pls see and try my steps

**Comment by wez** [comment]
Please share your logs; you haven't provided enough information for us to help you.
https://facebook.github.io/watchman/docs/troubleshooting.html#where-are-the-logs

I've been recommending folks to try to adopt `watchman-make` instead of a background trigger; it's easier for you to see what is happening and reason about when it is running.  It is focused around running things from a make file though, so it is a little different:

Docs for it are here: https://facebook.github.io/watchman/docs/watchman-make.html

**Comment by wez** [comment]
Please re-open with the logs when you get around to looking at this again.
