### ISSUE TITLE
does `watchman` kills previous build process?

### ISSUE THREAD

**Issue by lx93uv** [facebook/watchman#447]
When `watchman` detects file changes and invokes build processes - does it kills previous build, to leave only one build process active?

**Comment by wez** [comment]
I'm assuming that you are asking about triggers?

This is covered in the documentation:

https://facebook.github.io/watchman/docs/cmd/trigger.html

**Comment by lx93uv** [comment]
here is [demo](https://asciinema.org/a/5kaqn3a1sdub3jgwnxy0bouz8) and here is [sources](https://gist.github.com/lx93uv/5c94f8b853185610572d015b1558e97c)

Do you mean that killing of previous build process should be implemented as trigger command, right?

**Comment by wez** [comment]
OK, so you're talking about `watchman-make`.  Neither `trigger` nor `watchman-make` kill off the running process.  This is by design; we don't know that it would leave things in a reasonable state if we opted to kill things off.  In addition, many build processes do things like generate sources that are likely to match your build invocation trigger, so if we killed things off as files changed, the build would not make progress.

Both `trigger` and `watchman-make` are intended to be quick and easy solutions to spawning (relatively) short lived processes as files change.  If you have a long lived build process that you'd like to terminate early when certain files change, then the most robust thing to do is have that process establish a watchman subscription and use the information from that subscription to terminate at safe points in the build process.

Since you're using nodejs, this documentation is the most relevant for establishing subscriptions:
https://facebook.github.io/watchman/docs/nodejs.html

**Comment by lx93uv** [comment]
I think that `watchman` should support additional flag for this feature.

For example, I build `latex` doc on old laptop - I use tmpfs and [this](https://gist.github.com/lx93uv/ed715d0460084f5c1bc283dbc025ca06) script for making building easier.

And it will be more suitable to use `watchman` than "random" bash script.
