### ISSUE TITLE
Clockspec/clock ID confusion on Windows alpha

### ISSUE THREAD

**Issue by masaeedu** [facebook/watchman#480]
The clock ID I'm getting from `watchman since` on Windows looks a bit weird; it doesn't seem to match the two segment clock ID shown in the docs (`c:123:234`). I get something with four segments when I run `watchman since D:\depot\git\agentautodeditor\sampledata n:foo ''`:

```
{
    "version": "4.9.0",
    "is_fresh_instance": false,
    "clock": "c:1496775649:11508:1:63",
    "files": []
}
```

Is there actually any meaning to the segments in the clock ID, or is it just segmented arbitrarily? I'd appreciate if you could provide a bit more info on the specifics of clockspecs and clock IDs; the [documentation](https://facebook.github.io/watchman/docs/clockspec.html) on this is quite sparse.

**Comment by sid0** [comment]
The clock is an opaque value. Its format is not part of the stable API and (other than the special clock value `c:0:0`) has no guarantees.

That said, that is indeed how the clock behaves on current versions of Watchman.

**Comment by masaeedu** [comment]
@sid0 Okay, thanks. So just to confirm, any change to any part of the clock ID indicates changes to the file system, being monitored, correct?

**Comment by sid0** [comment]
No, clock IDs can change for all sorts of non-filesystem related reasons.

**Comment by wez** [comment]
regarding your question about why the since query bumps the clock, this documentation is helpful to understand how we synchronize the point in time that you placed your query with the stream of events coming from the operating system:

https://facebook.github.io/watchman/docs/cookies.html

The `clock` command doesn't (by default) use a sync cookie, which is why you don't observe the clock value changing.

As @sid0 said, the contents of the clock string are opaque and subject to change across releases; as you've discovered, we've already revised it once to add more data, and the code in the master branch has a "fat clock" concept to support source control aware queries that is pending documentation (on my list for this week).

With all that in mind, can I ask why you're interested in the contents of the clock string?  What is your higher level goal?  Sharing that will help us suggest how to implement it with watchman.

**Comment by masaeedu** [comment]
Ok, so how are you actually supposed to use clock IDs? My use case is a process that will be started up at arbitrary times to perform some expensive work on data from a large folder. I was assuming I could just treat the clock ID as a kind of "hash" for the state of the folder, storing it alongside cached results and reusing the cached result if the clockspec from `watchman` matches the clock ID.

I could receive a dump of all changed files from watchman, but I don't actually care what's changed (and there can be a *very* large number of changes); only whether the contents of the folder are identical to some prior state for which I already have cached output.

**Comment by masaeedu** [comment]
Thanks for the explanation @wez, I've tried to explain what I'm doing above. This source-control aware queries you're referring to sounds like it might be closer to what I'm actually looking for.

**Comment by wez** [comment]
The clock string is used by watchman to provide you the list of files that changed since that prior point in time.   The intended use is that you thread back the clock value result from one query and into the next so that you understand the incremental changes between those queries.   This matches the typical incremental `make` pattern used in most build tools.

It sounds like for your use case you just want to run the query and re-use the state if the files list is empty?

There are some features that help in computing and maintaining overall state.  I don't know if these quite match up to what you've described; these are better suited if you can perform incremental updates to the cached state.

## SCM aware queries

If you are using a mercurial repo you can use SCM aware queries.  These aren't in the main docs yet but the commit that introduced them has some reasonable info about using them:
https://github.com/facebook/watchman/commit/cb949e93018040c76458375b40538d8c4733e689

The intent is that you can use the mergebase to lookup your cached state, and then the list of changed files since that branch point in the repo to compute a delta.

We don't currently support git, but adding git support wouldn't be too much effort.  It is however not on our TODO list; we will happily accept PRs from folks that really need it sooner!

## Use the new `content.sha1hex` field to hash the files you care about

The docs for this also have not yet made it to the main site, but here's the commit that introduced them:
https://github.com/facebook/watchman/commit/c884bba3eb4ca7f03b4d9cf06774f3b50481c79d#diff-f7ca7066272dc8e646090e01d35434af

The idea here is that you'd set your query expression to match the files that are of interest in your cached state and then include the content hash in your query:

```
["query", "/some/path", {
   "expression":  ["match", "*.cpp"],
  "fields": ["name", "content.sha1hex"]
}]
```

This will cause watchman to give you a list of the matching files and their SHA1 content hashes.  You can then compute an overall hash for the state from this, as well as use the SHA1 content hash of individual files to determine whether you need to recompute state for that particular file.

**Comment by masaeedu** [comment]
> It sounds like for your use case you just want to run the query and re-use the state if the files list is empty?

Sort of, yes. Detecting changes relative to the last time I queried works for the basic case where you want to cache only one result. What I actually want however, is to be able to cache multiple results, indexed by a digest of the directory contents. So if a user adds a file, runs the process, then deletes the same file and runs the process again, a cached result should be used.

Essentially I need to amortize the cost of hashing the directory contents over the period when my process is not running (and watchman is). `"content.sha1hex"` seems perfect for this, provided it is computed as files are changed, instead of when the query is made. Just so I understand correctly: suppose a large number of files are modified while watchman is running, and the process comes to life and asks watchman for a list of file hashes. Will watchman be able to provide this instantly, or will it need to go through the directory and hash everything at that point?

**Comment by wez** [comment]
By default the hashes are computed on demand (and using multiple cores), but you can enable some options to heuristically compute the hash as file change.

https://github.com/facebook/watchman/commit/802d37abe570fef81547cac3d346eef69b3ec93b is the commit that added those options.

So you'd stick something like this in a file named `.watchmanconfig` in the watched root to enable it:

```
{
   "content_hash_warming": true
}
```

there are also some options to control the size of the cache (`content_hash_max_items`.  This defaults to 128k.  You want this to be set > the number of files in your tree, otherwise the cache will thrash), the maximum number of items that will be warmed up per settle (`content_hash_max_warm_per_settle`; default 1024.  You may want this to be larger if you have a lot of files changing all at once), and whether to defer settling until after the warm up has completed (`content_hash_warm_wait_before_settle`; this is mostly useful if you have a live subscription).

The term `settle` here refers to a brief idle period after receiving a burst of change notifications from the OS.  The default settings, if warming is enabled, mean that up to 1024 files will get hashed at each settle out.  If you have more files than this changing all at once you'll want to increase this setting to ensure that the hashes are computed in time for your next query.

**Comment by masaeedu** [comment]
Ok great, that's exactly what I was looking for. Thanks!
