### ISSUE TITLE
client.on('error') is it permanent ?

### ISSUE THREAD

**Issue by JayChandler** [facebook/watchman#489]
Hello 

I've a question. When the **error** event is emitted to the client is this a permanent error or does the client try to reconnect on the next command ?

Just asking for proper error handling

```
        client.on('error', function (e) {
             process.exit(0); // ? Correct way ?
        });
```

**Comment by wez** [comment]
I'd recommend that you create a new client object to attempt to re-establish a connection with the watchman service if your client is a long-lived process (some kind of server process).

It's a good idea to use some kind of back-off when doing that (eg: sleep for 1-2 seconds on the first attempt, then double that on the next and so on), so that you don't go into a busy loop trying to reconnect.

If your client is short-lived then you needn't reconnect; if you want to print a diagnostic and then `process.exit(1)` then that is also a valid strategy.

**Comment by JayChandler** [comment]
thx
