### ISSUE TITLE
Path parsing error on Windows?

### ISSUE THREAD

**Issue by benpeart** [facebook/watchman#490]
It seems there may be a path parsing error on Windows. Some sub-directory paths of watched directories generate "unable to resolve root" errors.  In the example below "C:/git-sdk-64/usr/src/git" works correctly but the subdirectory "t/trash directory.t2013-checkout-submodule" returns an error.

`$ echo '["query", "C:/git-sdk-64/usr/src/git", {     "since": 1497899747,    "fields": ["name"],       "expression": ["not", ["allof", ["since", 1497899747, "cclock"], ["not", "exists"]]]    }]' | watchman -j                                    {
    "version": "4.9.0",
    "is_fresh_instance": false,
    "clock": "c:1497566659:12460:2:17",
    "files": [
        ".git",
        "t/trash directory.t2013-checkout-submodule/.git",
        "compat/vcbuild/GEN.PKGS/zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8/lib/native/v140/windesktop/msvcstl/dyn/rt-dyn/x64/Debug/zlibd.pdb",
        "compat/vcbuild/GEN.PKGS/zlib.v140.windesktop.msvcstl.dyn.rt-dyn.1.2.8.8/lib/native/v140/windesktop/msvcstl/dyn/rt
.
.
.`

`$ echo '["query", "C:/git-sdk-64/usr/src/git/t/trash directory.t2013-checkout-submodule", {     "since": 1497899747,    "fields": ["name"],       "expression": ["not", ["allof", ["since", 1497899747, "cclock"], ["not", "exists"]]]    }]' | watchman -j
{
    "version": "4.9.0",
    "error": "unable to resolve root C:/git-sdk-64/usr/src/git/t/trash directory.t2013-checkout-submodule: directory C:/git-sdk-64/usr/src/git/t/trash directory.t2013-checkout-submodule is not watched"
}`

**Comment by wez** [comment]
That second case looks like the query is missing a slash; is that just a transcription error?  Looks like the query should be:

```
$ echo '["query", "C:/git-sdk-64/usr/src/git/t/trash directory.t/2013-checkout-submodule", { "since": 1497899747, "fields": ["name"], "expression": ["not", ["allof", ["since", 1497899747, "cclock"], ["not", "exists"]]] }]' | watchman -j
```

Can you share the output from `watchman version` so that I can tell which rev this was?

Thanks!

**Comment by benpeart** [comment]
No transcription error - was copy paste.  The actual directory name is "trash directory.t2013-checkout-submodule"

$ watchman version
{
    "version": "4.9.0",
    "buildinfo": "5e99349a22daab444e2f78761603a6b9b620fa1f 2017-06-08T22:08:19.0000000Z"
}

There must be something else going on in addition to the directory name as when I removed the directory and recreated it manually (instead of via the git test suite) then the query succeeds.  

I _don't_ see the exception error that says I need to remove the watched path and then add it back again so don't know if it is related to that error or not.

Some additional examples that cause errors in case you can derive a pattern that helps:

Watchman: unable to resolve root C:/git-sdk-64/usr/src/git/t/trash directory.t0090-cache-tree
Watchman: unable to resolve root C:/git-sdk-64/usr/src/git/t/trash directory.t3400-rebase
Watchman: unable to resolve root C:/git-sdk-64/usr/src/git/t/trash directory.t3701-add-interactive

**Comment by wez** [comment]
Does your log file indicate that watchman cancelled out the watch for that path?
If not, does your log may say something like `final ref on` ?
Can you share that region of the log file?
I'm wondering if we have another similar issue to the one resolved in https://github.com/facebook/watchman/commit/fb4994a6113f84f52b1bc58fded6380019b5f8a0

**Comment by benpeart** [comment]
[log.zip](https://github.com/facebook/watchman/files/1086177/log.zip)

The base path ("C:/git-sdk-64/usr/src/git") has not been canceled.  If I query against it directly (instead of the subdirectory) it succeeds.  

'$ watchman watch-list
{
    "version": "4.9.0",
    "roots": [
        "C:/git-sdk-64/usr/src/git"
    ]
}'

**Comment by wez** [comment]
Hmm, I think this might actually be expected behavior.

I don't see any watches being spun up for those paths in your log.  The path that you pass to to `query` has to be a watched root otherwise it won't know how to address your query.

The general best practice is to establish the watch before attempting to query.  This is the simplest way to do it, but is using the legacy `watch` command (more details on this below):

```
watchman watch $ROOT
watchman query ...
```

The mercurial `fsmonitor` extension uses a pattern like this, where it optimistically assumes that the watch is ready in order to shave off a few milliseconds in the common case:

```
result = client.query("query", hgroot, ...)
if result is error containing "not watched":
    client.query("watch", hgroot)
    result = client.query("query", hgroot, ...)
```

Both of the above examples use the legacy `watch` command.

Note that watchman has a watch aggregation feature and optional enforcement; we have this enabled at Facebook to prevent creating overlapping watches of very large directory trees.   https://facebook.github.io/watchman/docs/config.html#root_files and https://facebook.github.io/watchman/docs/config.html#enforce_root_files are settings that enable this.  When enabled, `watch` will fail unless you run it on the repo root.

(You can't easily enable this feature on windows at the moment because the default filename for the global configuration path is a unix path that cannot exist; I'll put up a diff to move this somewhere more reasonable this week).

The way to make this work correctly in all cases is to use `watch-project` (https://facebook.github.io/watchman/docs/cmd/watch-project.html) instead of `watch`.  It's not quite a drop-in replacement; `watch-project` will return the path to the watched root and an offset that you are expected to add to your query:

```
$ watchman watch-project C:/git-sdk-64/usr/src/git/t/trash directory.t2013-checkout-submodule
{
  "watch": "C:/git-sdk-64/usr/src/git",
  "relative_path": "t/trash directory.t2013-checkout-submodule"
}
```

Then issue a query that includes a `relative_root` parameter set to the `relative_path` field from the `watch-project` response (yes, the naming is slightly inconsistent!) and passes the `watch` field as the `root` in the query:

```
$ echo '["query", "C:/git-sdk-64/usr/src/git", { "since": 1497899747, "relative_root": "t/trash directory.t2013-checkout-submodule", "fields": ["name"], "expression": ["not", ["allof", ["since", 1497899747, "cclock"], ["not", "exists"]]] }]' | watchman -j
```

This is going to be a bit more fiddly to do in bash; it is "OK" to use `watch` as the use of `enforce_root_files` is not widespread.

**Comment by benpeart** [comment]
You are absolutely correct.  User error - sorry about that.  I even had a "TODO" in my current integration script to do exactly what you describe in the mercurial fsmonitor extension.
