### ISSUE TITLE
[homebrew] Fails to create state directory on initial run if installed outside /usr/local

### ISSUE THREAD

**Issue by alexkrolick** [facebook/watchman#495]
On initial run, watchman tries to create a state directory at `/usr/local/var/run/watchman/$USER-state`; this fails if `/usr/local/var/run/watchman/` does not exist, which seems to be the case if Homebrew is installed at a non-standard location like `$HOME/.homebrew`.

On my system the run directory is at `/Users/myusername/.brew/var/run/watchman`

macOS Sierra with Homebrew, but probably affects others

**Comment by wez** [comment]
Would you mind taking a stab at fixing that in the homebrew recipe?  I don't know what steps you took to install homebrew in a different location, but regardless, the issue sounds like it is with the homebrew recipe rather than in watchman itself; we require that the state directory be created with appropriate permissions at installation time and that is handled in the homebrew recipe.  I'd be happy to review those changes (just mention me in the homebrew PR).

**Comment by alexkrolick** [comment]
The directory is created, but watchman uses the wrong one

**Comment by wez** [comment]
Please file an issue with the homebrew project and mention this issue there.
