### ISSUE TITLE
ignore_dirs glob/regex?

### ISSUE THREAD

**Issue by eveliotc** [facebook/watchman#498]
Wondering if there is a way to ignore patterns example:

```
{
  "ignore_dirs": [
    "**/build"
  ]
}
```

Would ignore all the "build" named directories on the directory tree.

**Comment by wez** [comment]
Not today, no.  I've been resisting adding it because this whole feature is working around an anti-pattern; you should keep your build stuff out of the source tree.

While you may think that I'm opinionated about this (I am a bit!) there is a technical reason to avoid it: some operating systems (macOS and Windows) recursively watch the directory tree and deliver change notifications through to watchman anyway.

macOS has limited support for ignoring directories: it has a fixed limit of 8 paths that must be specified at the time that the watch is established.  There is no provision for pattern matching.

This means that there is a performance penalty for keeping your build artifacts in the tree.  The more there are and the more frequently they change, the harder your system is going to have to work to simply ignore those files.

So my recommendation would be: try to get those files moved out of your source tree, or if that isn't possible, put them under a single path at the root that you can ignore; eg: rather than `foo/build` and `bar/build`, have `build/foo` and `build/bar`.

You can then use a single `ignore_dir` entry for them, and get the (second best) possible performance on macOS.

**Comment by wez** [comment]
Labelling this as wontfix to indicate that we don't really want to fix this; it is better to fix the source of the noisy changes rather than trying to suppress them after paying the cost for receiving them.

**Comment by pauldraper** [comment]
> you should keep your build stuff out of the source tree.

I love the idea, and thi... 🚨🚨🚨 **NODE_MODULES** 🚨🚨🚨
