### ISSUE TITLE
'/usr/local/share/aclocal/mysql.m4' does not exist && watch null EMFILE

### ISSUE THREAD

**Issue by gaoxiaosong1113** [facebook/watchman#499]
使用
`brew install --HEAD watchman 
`
安装watchman 时提示
![image](https://user-images.githubusercontent.com/16183057/27775754-99baf298-5fd7-11e7-8843-aca72bd3a915.png)

安装完成以后使用-v查看版本信息会提示以下信息
![image](https://user-images.githubusercontent.com/16183057/27775789-d7dbe33e-5fd7-11e7-8838-6bb72043f02e.png)

在react-native 中使用 `react-native run-ios` 会提示以下错误
![image](https://user-images.githubusercontent.com/16183057/27775793-e22c6c6e-5fd7-11e7-94f3-1ead8624995d.png)

![image](https://user-images.githubusercontent.com/16183057/27775794-e6b894c4-5fd7-11e7-9586-b5866a40c9db.png)

请帮助我解决一下这个问题，谢谢~~~

**Comment by wez** [comment]
I'm sorry, but I can't read most of the text in this report.  Thank you for including a lot of information though; I think I can see what is going wrong!

Please try the following:

1. `npm uninstall watchman`.  The npm `watchman` package is unrelated to the Facebook watchman service and it conflicts in confusing ways.   I suspect you have the npm package installed because `watchman -v` gave you an error message instead of printing the version.

2. Don't use `--HEAD` when installing from homebrew.  Just use `brew install watchman`.  HEAD may not be stable, and building HEAD requires a working build environment (which is appears you don't have based on the error about mysql).  Installing the current released version is strongly recommended because it is often just a binary download and should avoid build environment issues.
