### ISSUE TITLE
Watchman starts 2 Bundling process instead of one in React Native

### ISSUE THREAD

**Issue by hugomosh** [facebook/watchman#531]
When I run react-native run-ios
The packager starts and after i get

Loading dependency graph, done.
Bundling `index.ios.js`  ▓▓▓▓▓▓▓▓▓▓▓▓▓░░░  86.6% (687/748)
Bundling `index.ios.js`  ▓▓▓▓▓▓▓▓▓▓▓░░░░░  70.1% (523/639)

So there are two Bundling instead of one and it is taking forever.

I already updated to watchman "4.9.0"

Any clues? It took me a while to find out that watchman is the problem here. 
With android doesn't seem to have the problem.
Is there some where a corrupted file, like a configuration file, cache or something??

**Comment by wez** [comment]
Please report react-native issues with the react-native project.  They're better equipped to help you understand what is going on and find a resolution.

Please keep in mind that watchman answers queries about changes to the filesystem.  It doesn't actively dispatch work in react-native; if RN is running two concurrent Bundling thingies then it is because RN decided to do so.  I'm doubtful that this issue is caused by watchman.

**Comment by hugomosh** [comment]
It has to do with https://github.com/facebook/metro/issues/253
