### ISSUE TITLE
Watchman causing a long initial delay when writing to some files on Windows

### ISSUE THREAD

**Issue by ChrisTrenkamp** [facebook/watchman#540]
I'm using the latest Watchman build on Windows 10.

I have a program that creates/edits/deletes some files in a directory.  When Watchman is running, the first change that happens in that directory has a very long delay (about 4 seconds, and each Watchman instance adds another 4 seconds).  After the initial delay, everything proceeds as normal.

I've verified that this only occurs when Watchman is running.  It doesn't seem to matter if Watchman is watching that directory or not, the initial delay still occurs.

**Comment by wez** [comment]
Sorry for the delay in responding, but I have good news.  What I think you were hitting was a combination of:

* https://github.com/facebook/watchman/issues/548
* 0968e377ca01448e5c56a7d391eddb3ed6431e20

The very latest build from appveyor today has fixes for both of these issues; you can find a link to it from the watchman download page.

I'm going to close this issue on the assumption that either you've moved on and don't care any more because of the amount of time that has elapsed, or that this new build did work out for you and solved your problems.
