### ISSUE TITLE
run watchman watch  /path/to/dir. get error!

### ISSUE THREAD

**Issue by happy201993** [facebook/watchman#541]
[cli] unable to talk to your watchman on \\.\pipe\watchman-Administrator! (No error)
environment: windows7

**Comment by wez** [comment]
Sorry for the late response, but there's not enough information to understand the issue here.
I'm going to close this out due to its age, but if you are still interested in resolving it, please re-open it and include your watchman log files.  The troubleshooting guide is something you should read through, too:
https://facebook.github.io/watchman/docs/troubleshooting.html

**Comment by DanGDroid** [comment]
updated link: https://facebook.github.io/watchman/docs/troubleshooting
