### ISSUE TITLE
FAIL: tests/art.t on Alpine Linux (musl libc)

### ISSUE THREAD

**Issue by TBK** [facebook/watchman#546]
I am trying to run the test suite on Alpine Linux (Musl Libc), unfortenatley the tests/art.t fails.

![image](https://user-images.githubusercontent.com/858296/32415769-06731dba-c23f-11e7-85dd-f81eb1529932.png)

**test-suite.log:**
```
======================================
   watchman 4.9.0: ./test-suite.log
======================================

# TOTAL: 11
# PASS:  10
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: tests/art.t
=================

1..84
ok 1 - tests/art_test.cpp:109 t.size() == 2
ok 2 - tests/art_test.cpp:146 l && l->key == "A"
ok 3 - tests/art_test.cpp:150 l && l->key == "zythum"
FAIL tests/art.t (exit status: 139)
```

**Comment by wez** [comment]
Can you run that test under gdb and get a stack trace?

```
gdb tests/art.t
run
bt all
```

**Comment by TBK** [comment]
Sorry about the delay. Here are the results of the commands:
![image](https://user-images.githubusercontent.com/858296/32553725-f95a1592-c497-11e7-99fa-dac41c550be0.png)

**Comment by wez** [comment]
Please share the output from `g++ -v`.

We don't have cycles to install and try this on Alpine linux, or on a system with musl libc.
Do you have the ability to try a different version of g++ on that system?  That might rule out a compiler bug.

My hunch is that this is a musl<->g++ problem rather than a watchman bug because this code has been running fine in production for years and we test it daily with ASAN enabled.

**Comment by wez** [comment]
I found some time to run the unit tests on an alpine linux system and found and resolved an issue.

Since Alpine seems rather anemic (missing packages such as PHP) I was not able to run the integration tests, and I'm unwilling to burn more time on this particular distribution; hopefully that's all that is needed here.

**Comment by olegsmetanin** [comment]
Alpine is very important in the docker-world. For those who use containerized development environment inside the docker, it would be useful to have an actual version of the watchman. The last working version in alpine - 4.7.0. https://github.com/smashwilson/node-watchman/blob/master/Dockerfile

**Comment by wez** [comment]
Alpine is not on our list of priorities.  Contributions from the community are warmly welcomed!

Note that since my last comment above, we've removed the PHP dependency for integration tests in master, so it may be that all that is needed is for someone on Alpine to run the tests and generate an issue for each failure, if any, and then we can look at getting those resolved.

We are overdue with running a release (lots of changes in master), but we don't plan on doing that in the immediate future.

**Comment by pklapperich** [comment]
`make -k check` also fails for me in test/art.t on Archlinux with glibc.

```
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-pc-linux-gnu/8.1.1/lto-wrapper
Target: x86_64-pc-linux-gnu
Configured with: /build/gcc/src/gcc/configure --prefix=/usr --libdir=/usr/lib --libexecdir=/usr/lib --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=https://bugs.archlinux.org/ --enable-languages=c,c++,ada,fortran,go,lto,objc,obj-c++ --enable-shared --enable-threads=posix --enable-libmpx --with-system-zlib --with-isl --enable-__cxa_atexit --disable-libunwind-exceptions --enable-clocale=gnu --disable-libstdcxx-pch --disable-libssp --enable-gnu-unique-object --enable-linker-build-id --enable-lto --enable-plugin --enable-install-libiberty --with-linker-hash-style=gnu --enable-gnu-indirect-function --enable-multilib --disable-werror --enable-checking=release --enable-default-pie --enable-default-ssp
Thread model: posix
gcc version 8.1.1 20180531 (GCC) 
```

```
$ gdb tests/art.t
GNU gdb (GDB) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from tests/art.t...done.
(gdb) run
Starting program: /home/paulk/fromsrc/watchmen/src/watchman/tests/art.t 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
1..84
ok 1 - tests/art_test.cpp:109 t.size() == 2
ok 2 - tests/art_test.cpp:146 l && l->key == "A"
ok 3 - tests/art_test.cpp:150 l && l->key == "zythum"

Program received signal SIGSEGV, Segmentation fault.
0x000055555555bab6 in art_tree<unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Node::minimum (
    this=<optimized out>) at ./thirdparty/libart/src/art.h:86
86	  static inline bool IS_LEAF(const Node* x) {
(gdb) bt all
No symbol "all" in current context.
(gdb) thread apply all bt

Thread 1 (Thread 0x7ffff7fb5780 (LWP 5306)):
#0  0x000055555555bab6 in art_tree<unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::Node::minimum (
    this=<optimized out>) at ./thirdparty/libart/src/art.h:86
#1  0x000055555555983c in art_tree<unsigned long, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >::minimum (
    this=0x7fffffffdca0) at /usr/include/c++/8.1.1/bits/unique_ptr.h:342
#2  test_art_insert_delete() () at tests/art_test.cpp:199
#3  0x0000555555558083 in main (argc=<optimized out>, argv=<optimized out>) at tests/art_test.cpp:423
```

This is with glibc 2.27 (archlinux package v2.27-3).

**Comment by logix2** [comment]
This also fails on Ubuntu 18.10:

``
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 8.2.0-7ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.2.0 (Ubuntu 8.2.0-7ubuntu1)
``

**Comment by jcea** [comment]
I have using "watchman" for for a couple of years in Ubuntu 16.04. I am migrating to Ubuntu 18.04 and hitting the same bug:

```
$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.4.0-1ubuntu1~18.04.1' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)
```

**Comment by wez** [comment]
v4.9.0 is a couple of years old and the entire code base has changed a lot in that time.
I realize that you're running v4.9.0 because that is the most recent tag, however, we're not going to apply a fix for that release.

I would suggest trying master but the build process is a bit laborious due to the increased set of dependencies (there are some notes on this in https://github.com/facebook/watchman/pull/754), however, I don't think this test failure has a practical impact and I'd suggest just ignoring it and running with the easier to build v4.9.0 until we finally manage to streamline the build enough that it isn't unreasonably difficult to build master outside of our build environment.

**Comment by jcea** [comment]
So, what you are saying is that current release (a couple of years old) is failing in current Linuxes and that master is not in an usable state? Catch22! :-).

I will keep using 4.9.0 with the provided patch and hope for the best :)

Thanks! :).

**Comment by wez** [comment]
I'm saying that that unit test failure has no correlation with any production problem that I've observed in our deployment across thousands of hosts over the multi-year lifetime of this project.  As such you can safely ignore that failure.

I'm not saying that either that tag or the master branch is unusable (we're running it in a huge deployment!) just that it will feel unreasonably difficult to build it outside of FB today due to the scope of the dependencies.  It is certainly possible to build, but I doubt most people will have the patience.
