### ISSUE TITLE
Error building watchman on OSX 10.9.5 

### ISSUE THREAD

**Issue by hahahatrick** [facebook/watchman#556]
I'm getting an error building from source on OSX 10.9.5:

```
FileDescriptor.cpp:663:56: error: use of undeclared identifier 'AT_SYMLINK_NOFOLLOW
```

I'm assuming this is an issue with using ```fstatat``` on OSX, is there an alternative to this command, maybe ```stat```?
https://github.com/facebook/watchman/blob/d3a486c08c8592a7b623eb033947dd86a11ed3ff/FileDescriptor.cpp#L662

**Comment by wez** [comment]
We don't have a need to make watchman run on such an old version of macOS, and in this case, it's rather difficult to implement the strict case and path checks that we require without it.   Can you upgrade to a more recent version of macOS?

Alternatively, you may be able to build and run an older version of watchman.  We don't recommend that as any problems you encounter will be an exercise in re-discovering old bugs that we've already fixed in the past several years :-/
