### ISSUE TITLE
Watchman is not working with Jest on Windows

### ISSUE THREAD

**Issue by FredyC** [facebook/watchman#570]
It's quite interesting that this is not reported in here yet (or am I really that bad with search?).

I would reference two issues from Jest repo which includes many details and add that this is still an issue with Watchman 4.9.1 and Jest 20.0.4

https://github.com/facebook/jest/issues/2219
https://github.com/facebook/jest/issues/4108

Using option `--no-watchman` is a viable workaround, although we are not getting benefits of Watchman. I think that this should be addressed before Beta goes Stable.

**Comment by wez** [comment]
There's not really anything we can use to troubleshoot this here.  What isn't working?  What watchman commands are being run?  What is their output?  What is jest expecting?

Please keep in mind that while both jest and watchman are projects from Facebook, the folks that work on them don't necessarily use each others tools on a daily basis, and throwing windows in to the mix makes it that much harder for the folks on both of these teams to speculatively try to repro the issue... because Windows isn't the primary development platform for either group!

We are interested in understanding more so that we can work out a fix, but we're relying on folks such as yourself to go that extra mile to write up a really good and deep problem report to help point us in the right direction.

Can you dig in and get a small repro scenario going, and then add some logging to capture what is going in and out of watchman?

**Comment by FredyC** [comment]
I can certainly try to collect more intel here. Seeing how many people got burned by this and none was able to give any details, I do have doubts about my success :)

Can you help me out here where is the default location for the Watchman logs on Windows? I've been looking into docs, but everything seems *nix specific.

**Comment by wez** [comment]
@FredyC thanks!  TBH, you're probably better off adding logging in the jest code around its calls to the watchman module.

Re: windows logs, we need to update https://facebook.github.io/watchman/docs/troubleshooting.html#where-are-the-logs to cover this.
They're in `%TEMP%\%USERNAME%-state\log`.  I don't think you'll find much of use in there unless watchman is encountering an error;  I suspect that this issue boils down to how jest is integrating with watchman rather than watchman experiencing a problem... but it can't hurt to check!

**Comment by FredyC** [comment]
Ok, so I found out that this is actually fixed with Jest 22 (and confirmed). So it seems it wasn't Watchman's fault in the end 😊 I am sorry for bothering you here, but at least people looking for this issue will hopefully find this finding useful :)

_And as a bonus a could point out for a missing Win docs_ 😏

https://github.com/facebook/create-react-app/issues/2889#issuecomment-356299130
