### ISSUE TITLE
support watch-del for consolidated roots

### ISSUE THREAD

**Issue by aleclarson** [facebook/watchman#609]
When `watch-project` roots are consolidated based on shared `.git` history (is that the only time consolidation occurs?), `watch-del` commands don't work as expected. You're forced to use the common root with `watch-del`, instead of the `watch-project` roots. The problem there is that clients will need to track which `watch-project` roots share a common root, as to avoid sending a premature `watch-del` command.

Watchman could keep a "retain count" for its common roots, allow `watch-del` to always work with `watch-project` roots, and perform the actual `watch-del` job once its retain count hits zero.

**Comment by wez** [comment]
The intent is that no one should really be thinking about `watch-del` at all, because critical components in our infra do not have long running connections to watchman (eg: mercurial and git fsmonitor extensions).  With that in mind, there is no way to reference count watches safely.  Instead, watchman will age out and retire idle watches after about a week (this is configurable).

Tools and automation should not be running `watch-del` unilaterally because they will break the performance of other consumers by causing watchman to recrawl, which can take several minutes on loaded systems with very large repos.   (One exception to this is for CI: when the CI job is finished, it makes sense for it to cancel the watches because it totally owns the isolated build environment, and won't mess things up for other consumers)

`watch-del` is considered to be a troubleshooting command rather than a common workflow command.
