### ISSUE TITLE
Warning about the old version

### ISSUE THREAD

**Issue by qumuase** [facebook/watchman#626]
```
11:25:08: Warning: You are using an old version of watchman (v4.5.0). This may cause problems for you.
11:25:08: We recommend that you either uninstall watchman (and XDE will try to use a copy it is bundled with) or upgrade watchman to a newer version, at least v4.6.0.
11:25:08:
11:25:08: If you are using homebrew, try:
11:25:08: brew uninstall watchman; brew install watchman
```
I followed the prompts to uninstall and reload, and through watchman -v to see that the version is already 4.9.0, but still re-running is still an error.
I don't know what to do with it.
thank you very much!

**Comment by wez** [comment]
Sorry for the lag in responding here.  `watchman version` will query the running server and tell you the version that is running, whereas `watchman -v` tells you the version of the CLI.  Sometimes upgrading watchman will not restart the server in which case running `watchman shutdown-server` is the right thing to do.

I don't know where that warning text is coming from, but if some other software package has bundled an old version of watchman it is possible that it is deliberately running that version instead of the one you want to use.  You should consult with whomever supports the software that printed out that warning to understand what is really happening.

**Comment by qumuase** [comment]
@wez thank you very much!
