### ISSUE TITLE
Watching .git/refs/** at runtime?

### ISSUE THREAD

**Issue by themightychris** [facebook/watchman#664]
I'm developing a tool that can be switched between watching a working tree and just watching for new commits to refs in a git repo.

I've run into what seems like a hurdle that `ignore_vcs` can't be changed at runtime. Based on the runtime config/flags to my tool, I either want to watch the working tree with `ignore_vcs`=`.git` in effect or I want to only watch `.git/HEAD` and `.git/refs/**`

Is there any way to change `ignore_vcs` in the context of `watch-project` or `subscribe`? It seems like this option could only be changed by the user outside of using my tool, and there's no way my tool could switch modes without the user toggling watchman config?

**Comment by wez** [comment]
Sorry this slipped through the cracks.  We can't cheaply change `ignore_vcs` at runtime because it requires recrawling the entire tree to take effect, and our namespace is the filesystem: we can't allow for conflicting configurations on the same path (eg: most tools won't want the behavior you want, but if you apply that setting, then they are broken by it).

My suggestion would be that you either watch the directory containing the `.git` dir when you're watching the working copy, or cancel that watch and then watch the `.git` dir itself when you want to focus on that portion.

I would advise against trying to watch both at the same time because that can lead to performance problems.

You may find that you need to place a `.watchmanconfig` in the `.git` directory in order to avoid the default behavior of preferring to watch the repo directory that contains the `.git` directory.

**Comment by themightychris** [comment]
thanks @wez ! That sounds workable
