### ISSUE TITLE
wildmatch glob syntax undocumented

### ISSUE THREAD

**Issue by conartist6** [facebook/watchman#729]
If someone will explain to me what glob syntaxes are supported, I will open a PR to update the docs.

As far as I can tell only `**` and `*` are supported. Many people are used to working with glob implementations which support more syntaxes than this, so offering clarity on what is supported would be great. In general I think it's just good practice to always define possible syntaxes.

**Comment by conartist6** [comment]
It seems that the syntax is git's matching syntax, e.g. as used in .gitignore. The assumption I suppose is that programmers would know that git's implementation is called wildmatch, but this is not a safe assumption, and it would be useful to link to one of any number of docs which explain that syntax in full.

**Comment by conartist6** [comment]
In addition to documenting exactly what is supported, it would also be nice to support more glob syntaxes. It seems like it might make sense to bake in [fnmatch](http://man7.org/linux/man-pages/man3/fnmatch.3.html) instead of wildglob. Additional supported functionality like extglob could be exposed as a capability and would require being specified in match options.

**Comment by wez** [comment]
The supported syntax is shell style pattern matching with support for recursive wildcards.
We use an original implementation that was written by Rich $alz back in 1986, and that was expanded to support recursive (`**`) wildcards.   Character classes and negated character classes are supported, along with single character (`?`) and multi-character (`*`) wildcards.

FWIW, we don't use `fnmatch` any longer because its behavior varies across platforms, typically has fewer features, and it also does not support recursive pattern matching.

This commit has some more information on the origins of this code:
https://github.com/facebook/watchman/commit/471138f2cbcea1c974a7c539a4522fa741738cf4#diff-63ff1e2fef466171edb08a888a18e36c

Since this same implementation is/was used in rsync, you could potentially use its documentation (if any) to form the basis of a PR that you might prepare for watchman.

However, take care with the license: rsync is broadly GPL which is not compatible with our Apache style license, so we cannot directly copy GPL licensed documentation without explicit permission to re-license and use it here.

As an alternative approach, you could produce documentation by reading through the code; it isn't especially tricky if you are used to skimming through C code from the '80s:
https://github.com/facebook/watchman/blob/master/thirdparty/wildmatch/wildmatch.c
and looking at the unit tests for examples of different patterns:
https://github.com/facebook/watchman/blob/master/tests/wildmatch_test.json
(which is driven by https://github.com/facebook/watchman/blob/master/tests/wildmatch_test.cpp)

Regarding expanding the syntax: we'd be happy to accept a PR for that too; as you recognized in your comment, that functionality would need a capability to allow clients to know that they could make use of the new syntax.
