### ISSUE TITLE
xattr support

### ISSUE THREAD

**Issue by rektide** [facebook/watchman#735]
Hello. I would like to be able to detect when extended attributes on my files change (xattr). At the moment I'd be happy to know when any xattrs change in a given fs tree. More advanced implementations might let me match on which attribute, or further match by attribute's value, but for now, I'd just like to be made aware of which files have xattr() changes happening.

I'm not sure if Linux &c currently have a normative way to watch for xattr changes. If not, I'd suggest the problem be decoupled some: a eBPF tracing program could be written & applied to processes to watch for setxattr syscalls & to pick out the patch & that watchman could look at that feed & try to generate events where it finds matching project paths.

**Comment by wez** [comment]
It may sound strange but watchman doesn't work in a way that makes exactly what you asked for feasible.

Watchman builds a model based on its last observation of the filesystem.  It doesn't record or maintain a journal or log of how the filesystem changed over time because that would be infeasible from a space and time complexity perspective.

The result of this is that, when performing `since` queries, we can only answer with the list of files that changed since the earlier point in time and their *current* metadata.   We don't know how that metadata looked at an earlier point in time, only how it looks right now.  As a result, we can't diff the current state against the earlier state and thus can't constrain a query to be something like "only changes to extended attributes".

The best that we could do for this sort of use case is something similar to the way that we handle symlink targets or content SHA1 hashes of files: we could potentially add a cache for the list of extended attributes so that we could return the current value at the time of the query.

It would then be up to the consuming application to remember the older version of the extended attributes and, when processing results from watchman, decide whether they have changed.  It's worth noting that if the consuming application is maintaining that information then there isn't a lot of added value to having watchman cache extended attribute values.

**Comment by rektide** [comment]
@wez I'd be happy with something that I hope would be simpler:

> At the moment I'd be happy to know when any xattrs change in a given fs tree.

(I would hope this includes which file or files changed, but if not, I'll still take it. I'll take any kind of xattr integration, even if it means reloading the world and doing a VDOM style diff between my apps new world & the old one.)

Would the potential cache that gets added not also be everything needed to generate the change? It's a little tricky because you either have to make the "cache line" be the entire set of xattr's for a file, or you need to keep both the cache of individual xattrs, and have some way to enumerate all the xattrs a file has in the cache. I'm pretty sure I'm on like a 202 introductory level here & you're in the 700's graduate classes on all this, but your explanation didn't quite click into place for me like I expected, even though I felt like I was kind of following along.

Thanks for the kind reply. Much appreciated.

**Comment by wez** [comment]
> Would the potential cache that gets added not also be everything needed to generate the change? 

No it wouldn't be enough to guarantee that we generate a notification in all possible situations, and the results would be inaccurate with a worrying degree of probability.  There are a couple of factors:

* The cache would only be consulted for queries that explicitly request that metadata.  Multiple tools can be watching the tree and not all of them care about all of the same metadata.  This means that the model would be updated on-demand only, and at a point in time *after* the change was detected, and thus that it is not a guaranteed perfect representation of the state on the prior query results.
* The cache has a limited size and the prior state for some number of entries could have been evicted, again, meaning that we won't have a perfect representation of the prior results.
* Even with a perfect representation of the state of the last query, that isn't sufficient to answer any arbitrary query correctly.  Having a second client that is slightly out of sync with the first client could result in different data being reported to those clients!

This all adds up to a non-deterministic and unreliable result.

Filesystem watching is so fraught with TOCTOU that I strongly recommend keeping your integration as dumb as possible.  When xattrs are changed, watchman will already report that the file has changed (it just doesn't know what the cause was).  I would recommend that rather than trying to figure out how xattrs have changed to gate your application logic, that you just look at the current state and re-process the file.  That way you can't miss changes; it is more important to not miss changes than it is to save the occasional spurious re-processing of a file.
