### ISSUE TITLE
tests/bser.cpp test failure on Debian/s390x

### ISSUE THREAD

**Issue by aweeraman** [facebook/watchman#762]
We're seeing a test failure on the Debian/s390x architecture build:

Package: watchman
Version: 4.9.0-1
Source Version: 4.9.0-1
Distribution: sid
Machine Architecture: s390x
Host Architecture: s390x
Build Architecture: s390x

```
not ok 213 - raw bser comparison [1, 123, 12345, 1234567, 12345678912345678]
    Failed test (tests/bser.cpp:check_serialization() at line 186)
not ok 214 - raw bser comparison [1, 123, 12345, 1234567, 12345678912345678]
    Failed test (tests/bser.cpp:check_serialization() at line 186)
```

[s390x_debian_build.txt](https://github.com/facebook/watchman/files/3832049/s390x_debian_build.txt)

Thoughts appreciated. thanks.

**Comment by aweeraman** [comment]
The build also appears to fail on a few other architectures due to this same issue: https://buildd.debian.org/status/package.php?p=watchman

**Comment by wez** [comment]
Those are all relatively exotic architectures that we can't test on because they are not available in any CI system that have access to.
In addition, the 4.9.0 code base is rather old now (building master is admittedly difficult at the moment).
This issue is likely to remain unresolved (and likely closed as "wontfix") unless someone in the community with access to one of those systems steps up to investigate and submit a PR.
