### ISSUE TITLE
ext4 filesystem is not supported?

### ISSUE THREAD

**Issue by ashwin** [facebook/watchman#79]
I installed watchman so that I can use the [hgwatchman](https://bitbucket.org/facebook/hgwatchman/) extension for Mercurial. After I enabled the Mercurial extension, I tried `hg status` in a couple of my repositories.

I noticed these lines in my `/tmp/.watchman.myusername.log`:

```
1423557757: tid=713017088 path /home/myusername/somerepositoryname is on filesystem type unknown
1423558146: tid=713017088 path /home/myusername/otherrepositoryname is on filesystem type unknown
```

These repositories are in a `ext4` partition. Is this filesystem not supported by watchman?

**Comment by wez** [comment]
This just means that watchman doesn't know what to call the filesystem.
watchman will still work; you can safely ignore this message.

The only reason that watchman is interested in the filesystem type is so that an administrator can control whether we try to watch on a particular filesystem type.  This is typically used with remote filesystems such as NFS or CIFS.  You can find out more about that in https://facebook.github.io/watchman/docs/config.html#illegal-fstypes

**Comment by ashwin** [comment]
Thanks for the update @wez! I will close this issue :)
