### ISSUE TITLE
Copyright in help command ends in 2017

### ISSUE THREAD

**Issue by orta** [facebook/watchman#816]
Low priority, but after installing watchman via linux brew and running `watchman` the final bit of information says:

> Watchman, by Wez Furlong.
> Copyright 2012-2017 Facebook, Inc.

Might be worth making that 2012-Present, or maybe stamp the year in during the build process.

**Comment by udf2457** [comment]
@orta, I'm not a lawyer, but I suspect one would argue that "_present_" is not valid syntax.

**Comment by wez** [comment]
FWIW, you most likely installed v4.9.0 which was tagged in 2017 which makes that date range current for the tag.

**Comment by udf2457** [comment]
@wez 4.9.0 is still described as the current version (https://facebook.github.io/watchman/docs/release-notes)

**Comment by wez** [comment]
Yep.  Most of the changes in master since then have been to support [EdenFS](https://github.com/facebookexperimental/eden) (which you can't really use outside of FB today) so you needn't have FOMO :-)

master has been difficult to build outside FB for a while but we're on the cusp of "officially" updating things to point to the new automated weekly tags.  Just need enough bandwidth to get continuous binary builds publishing via GH actions along with the tags and we can make a pass over the docs and things like homebrew.

**Comment by udf2457** [comment]
Thanks @wez so (going slightly off-topic) is EdenFS the new Btrfs ? 

Indeed seems to be luck of the draw on getting master to build.  It seems to build ok on SuSE LEAP, but complains bitterly on Debian (unless `--enable-lenient` is set).

**Comment by wez** [comment]
master doesn't use autoconf any more (we switched to cmake a while back) and doesn't use warning->error promotion, so the `--enable-lenient` option shouldn't apply to anything any more.  The `autogen.sh` script will build most of the world needed to build watchman independent of system installed packages; aside from being time consuming it *should* be a successful build.

**Comment by udf2457** [comment]
Thanks @wez.  I certainly needed `--enable-lenient` following the recommended `git clone https://github.com/facebook/watchman.git -b v4.9.0 --depth 1` pull of the code.  Are you saying people should really just be following master these days and not the 2017 vintage `v4.9.0` tag ?

**Comment by wez** [comment]
No, stick with v4.9.0 until we update the docs to indicate otherwise.
However, I would appreciate feedback on your build experience from master if you have time to try that on your SuSE system.
