### ISSUE TITLE
watchman refuses to use inotify on FUSE filesystems

### ISSUE THREAD

**Issue by GeyseR** [facebook/watchman#831]
Unfortunately, after upgrading watchman to the latest version (v2020.07.13.00) from 4.9.0 it started failing to run.
I have a simple docker container running under the Docker for Mac application. It shares a volume with the host machine (mounted to the `/code` path) and running `watchman watch /code` fails with the following error:
```
# watchman watch /code
{
    "version": "20200712.162157.0",
    "error": "RootResolveError: unable to resolve root /code: inotify: cannot watch FUSE file systems with inotify. "
}
```

Is it possible to resolve, or such installation isn't supported by watchman?

**Comment by wez** [comment]
Oh interesting.  What is the filesystem that is mounted on `/code`?
Please share the `mount` output for it (eg: `mount | grep /code`)

We added this check in https://github.com/facebook/watchman/commit/8d54fa5625bb23d8af0bbb8ad7c52e656009a5f3
because FUSE filesystems need to do some explicit work to flag changes (lots of information in https://github.com/libfuse/libfuse/wiki/Fsnotify-and-FUSE).

Similar to network mounted filesystems, changes made through the local kernel will typically emit inotify events, but those on a remote system will not do so without some explicit support.

If your usage is local only then I think we could reasonably add some configuration so that the default would be to deny a watch (because we cannot 100% guarantee correctness) but allow overriding this check in some way.

**Comment by GeyseR** [comment]
Hi @wez,

Thank you for the quick response!

The `mount` command returns the following output on my machine:

`osxfs on /code type fuse.osxfs (rw,nosuid,nodev,relatime,user_id=0,group_id=0,allow_other,max_read=1048576)`

> If your usage is local only then I think we could reasonably add some configuration so that the default would be to deny a watch (because we cannot 100% guarantee correctness) but allow overriding this check in some way.
That would be really great, my use case is related exclusively to the local development!
I've seen the commit you pointed and that was the primary trouble that I wasn't able to workaround.

I've created a github repo for illustrate the problem and let you reproduce the bug in your environment: https://github.com/GeyseR/watchman-issue-831. You or someone else should use docker for mac, because our team wasn't able to reproduce the bug on a machine with VBox installed for the Linux virtualization (required for docker)

Hope that helps
