### ISSUE TITLE
Notification Feature on Slack & Email

### ISSUE THREAD

**Issue by sjkeerthi** [facebook/watchman#868]
Hi 

It will be great if we add any setting for email & slack notification systems for any changes will be great. 

It can be like a cronjob to send those .txt file as attachment on slack & email.

**Comment by wez** [comment]
This isn't something that we'll build directly into watchman, but should be fairly straightforward for someone to build using eg: the fb-watchman (nodejs) or pywatchman client bindings so that they can customize exactly what happens and how often and integrate it into their own particular process/flow.
