### ISSUE TITLE
Watchman and scss : trying to get a simple example to work 

### ISSUE THREAD

**Issue by rhacker** [facebook/watchman#89]
I really love to make watchman work for me, but somehow it doesn't work. Here is what I have tried : 

```Makefile
SASSC=sass

# CSS
watch:
        watchman watch $(shell pwd)
        watchman -- trigger $(shell pwd) remake *.scss -- make dist/main.css

dist/main.css: css/main.scss
        $(SASSC) $< > $@

.PHONY: dist/main.css watch
```

The problem when I change `css/main.scss`. Watchman triggers the build, and the make command doesn't seem to do the same thing when I run it in shell. I have an error ( shown below ) and from now on, watchman doesn't run the trigger on watched files anymore. 
```
1427610755: tid=3675723520 envp[52] CACHE_FLAG=0
1427610755: tid=3675723520 envp[53] LEIN_ROOT=1
1427610755: tid=3675723520 envp[54] TMUX=/tmp/tmux-0/default,90,0
1427610755: tid=3675723520 envp[55] GOROOT=/usr/local/go
1427610755: tid=3675723520 envp[56] REDIS_PORT_6379_TCP_ADDR=172.17.0.2
1427610755: tid=3675723520 trigger /var/www/html:remake pid=6621 ret=0 Success
make[1]: Entering directory `/var/www/html'
sass css/main.scss > dist/main.css
make[1]: Nothing to be done for `css/main.scss'.
make[1]: Leaving directory `/var/www/html'
```

**Comment by wez** [comment]
I think you need to quote `'*.scss` in your trigger line, otherwise the shell will expand it to the list of matches that were present at the time you ran `make watch` and watchman won't know to run for any added files.

If that's not the issue that you're hitting, can you respond with more details on what files you're changing (and how) and what you expect watchman to do, along with the output from `watchman watch-list` and `watchman trigger-list $PWD`?

**Comment by wez** [comment]
Closing this out for now.  Please re-open with the information requested if you'd like some help in moving forwards.  Thanks!

**Comment by rhacker** [comment]
Sorry for late responding. Thanks for closing it for now :)

**Comment by mattdipasquale** [comment]
Not sure if this is causing your issue, but I don't think dist/main.css should be listed as .PHONY.
