### ISSUE TITLE
Watchman windows zip flagged as containing Trojan(s)

### ISSUE THREAD

**Issue by alpinstang** [facebook/watchman#890]
I thought it might be a false positive but VirusTotal is saying 6 scanners flag it as unsafe. Can anyone explain why? Is it a compromised download?

[VirusTotal Scan](https://www.virustotal.com/gui/file/c5be1c0e3063cbb72a193e2448fb45107d6d70f92c380175f24a96b8ff381f14/detection)

**Comment by fanzeyi** [comment]
Hi, thanks for flagging. It is definitely a false positive caused by a recent feature addition of automatically _dropping privileges_ on Windows if Watchman is started with Administrator privileges. We added this because there are many cases of people accidentally starting Watchman daemons causing other clients with normal privileges not able to talk to Watchman.

In VirusTotal's analysis, if you expand the details you will see they are actually flagging `eledo-pty-bridge.exe` as potential threats (see screenshot below). The source code for that particular thing can be found at https://github.com/wez/Eledo if you want to take a look.

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/409951/106411719-c4395e80-63fa-11eb-9f32-e1dfd8167868.png">

We had a similar report in #886, and I have reported to Microsoft about the false positive case for `watchman.exe` itself. Let me try to submit `eledo-pty-bridge.exe` and see if they can remove this false positive.

**Comment by alpinstang** [comment]
Thanks for the update. Hopefully they will get that process unflagged.

**Comment by lukeapage** [comment]
Windows defender still blocks this file for me :(

**Comment by robatwilliams** [comment]
Today I also have it blocked by Windows Defender. On Friday it wasn't blocked. My current virus & threat protection update is 11/04/2021 20:55 (GMT+1).

The symptom is "Failed - virus detected" shown by Chrome.

**Comment by fanzeyi** [comment]
@lukeapage @robatwilliams  Thanks for all the reports. I'm going to re-submit it again to Microsoft for another scan. Sorry about it. I will update as soon as I heard back from them.

**Comment by robatwilliams** [comment]
Our security team also submitted a false detection to Microsoft, they had an alert due to what I did and followed the process they have. Further info they asked for, in case it's more useful than the date I previously gave:

```
PowerShell:

Get-MpComputerStatus
AntivirusSignatureVersion       : 1.335.639.0
````

**Comment by fanzeyi** [comment]
Microsoft completed the analysis and they have removed the detection. Please try updating the malware definitions with these steps:

> We have removed the detection.  Please follow the steps below to clear cached detection and obtain the latest malware definitions.
>
>     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
>     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
>     3. Run "MpCmdRun.exe -SignatureUpdate"
>
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

**Comment by robatwilliams** [comment]
No problems with `AntivirusSignatureVersion       : 1.335.706.0`
