### ISSUE TITLE
Deprecated command on homepage

### ISSUE THREAD

**Issue by gkze** [facebook/watchman#899]
In the "Quickstart" section of the homepage the command to start watching a filesystem path is:
```
watchman watch ~/src
```
When looking at the [docs for `watchman watch`](https://facebook.github.io/watchman/docs/cmd/watch.html), there is a notice of deprecation recommending `watchman watch-project` instead. Should the homepage be updated to reflect this and show the new command instead?

**Comment by xavierd** [comment]
Good catch! I've sent a code review internally to fix this, this should be corrected soon :)

**Comment by wez** [comment]
FWIW, the semantics of `watch` vs. `watch-project` are different: `watch` will either watch what you asked or it wont, whereas `watch-project` will watch some path with an offset that you must carry around in subsequent queries in order to have correct results.

The quickstart guide is human facing so it uses the simpler semantics of `watch`.  Tools should use `watch-project` rather than `watch`.   The distinction doesn't mean much in the default configuration, but sites that deploy [enforce_root_files](https://facebook.github.io/watchman/docs/config.html#root_files) configuration can only use tools that use `watch-project`, or that are careful to respect the restriction.

It's fine that the quickstart references `watch`.  Per the published https://facebook.github.io/watchman/docs/compatibility.html rules, the `watch` command will continue to exist forever.

**Comment by gkze** [comment]
Thank you @wez - that's great to know. I guess it isn't much of a problem with this context.

**Comment by gkze** [comment]
Is this already clarified somewhere? Apologies if I missed this information in the docs - I'd be happy to close this issue if that's the case.
