### ISSUE TITLE
Linux: quickly deleting and creating a file is reported as a single event

### ISSUE THREAD

**Issue by bpasero** [facebook/watchman#980]
Running watchman on Linux triggering a delete followed by create on a file emits a single event:

```json
{
  "name": "<path>"
  "exists": true,
  "size": 11,
  "mode": 33204,
  "new": true
}
```

This was observed when executing the following node.js script:

```js
const fs = require("fs");
fs.unlink("<path>", () => {
  fs.writeFile("<path>", "Hello World");
});
```

I would have expected to receive a delete event followed by a create event. This enables upstream clients to coalesce this condition into a change event, given this is a somewhat atomic write operation. Alternatively, I would have expected watchman to emit a change event instead.

**Comment by chadaustin** [comment]
This is expected behavior. Watchman does not give a complete event stream (and sometimes we don't even get a complete event stream from the OS!) but will report every change in the end.

Note that the "new" field is somewhat nonsensical, and we've talked about removing it. It's meaning is complicated and fuzzy, so I wouldn't rely on it for anything.
